### ISSUE TITLE
add --quiet option

### ISSUE THREAD

**Issue by RichMorin** [openstreetmap/osm2pgsql#777] opened 2017-07-30 02:44 UTC
To indicate its progress, osm2pgsql uses a line of the form "Processing: Node...", which uses embedded carriage returns to update in place. Consequently, the output stream contains a huge number of lines, separated by carriage returns.  This isn't a problem for most use, but it doesn't play nicely with script(1). Please consider turning this feature into an option:

- `-q 1 | --quiet 1` could cause the program to print a single summary line.
- `-q 2 | --quiet 2` could cause the program to print a dot for each unit of processing.

**Comment by lonvia** [comment] 2017-07-30 05:37
Duplicate of #591.

**Closed by lonvia** 2017-07-30 05:37 UTC
