### ISSUE TITLE
Add an option to prevent DROP CASCADE in -create mode

### ISSUE THREAD

**Issue by nextstopsun** [openstreetmap/osm2pgsql#763] opened 2017-06-01 11:50 UTC
Please add an option to prevent `DROP CASCADE` of imported tables before filling them up in `-create` mode. It can be false by default.
I have a lot of views depending on those tables, and they all get dropped when refilling osm data from scratch.
I know I can `TRUNCATE` manually and use an `-append` mode, but it's so much slower than `-create`.
I guess such an option shouldn't do no harm, but introduce some benefits instead.

**Comment by lonvia** [comment] 2017-06-01 12:04
Duplicate of #758.

**Closed by lonvia** 2017-06-01 12:04 UTC
