### ISSUE TITLE
Upper case prefix results in error

### ISSUE THREAD

**Issue by mzeedijk** [openstreetmap/osm2pgsql#1420] opened 2021-02-16 16:28 UTC
When using a prefix like DEU (note: uppercase) osm2pgsql stops with the message that DEU_nodes does not exist.
The tables were created, but about half of them with uppercase prefixes and the rest with lowercase prefixes.

Command used in our scripts:
osm2pgsql -U postgres -d planet -H 127.0.0.1 --drop -c -C 8000 --slim -k -E 4326 -v --hstore-match-only --number-processes 2 --prefix DEU -S /root/osm2pgsql.style /root/DEU.osm.pbf

Output:
2021-02-16 17:05:06  osm2pgsql version 1.4.1
2021-02-16 17:05:07  Database version: 12.5 (Ubuntu 12.5-1.pgdg18.04+1)
2021-02-16 17:05:07  PostGIS version: 3.1
2021-02-16 17:05:07  Reading file: /root/DEU.osm.pbf
2021-02-16 17:05:07  Allocating memory for dense node cache
2021-02-16 17:05:07  Allocating dense node cache in one big chunk
2021-02-16 17:05:07  Allocating memory for sparse node cache
2021-02-16 17:05:07  Sharing dense sparse
2021-02-16 17:05:07  Node-cache: cache=8000MB, maxblocks=128000*65536, allocation method=11
2021-02-16 17:05:07  Mid: pgsql, cache=8000
2021-02-16 17:05:07  Setting up table 'DEU_nodes'
2021-02-16 17:05:07  Setting up table 'DEU_ways'
2021-02-16 17:05:08  Setting up table 'DEU_rels'
2021-02-16 17:05:08  Using projection SRS 4326 (Latlong)
2021-02-16 17:05:08  WARNING: Unknown flag '0' line 48, ignored
2021-02-16 17:05:08  Using built-in tag transformations
2021-02-16 17:05:09  Setting up table 'DEU_point'
2021-02-16 17:05:09  Setting up table 'DEU_line'
2021-02-16 17:05:09  Setting up table 'DEU_polygon'
2021-02-16 17:05:09  Setting up table 'DEU_roads'
Processing: Node(10k 10.0k/s) Way(0k 0.00k/s) Relation(0 0.0/s)2021-02-16 17:05:10  ERROR: DB copy thread failed: Database error: ERROR:  relation "DEU_nodes" does not exist

**Comment by joto** [comment] 2021-02-16 18:29
I can reproduce that bug. The reason is that PostgreSQL handles plain tables name differently than it handles quoted names. So `CREATE TABLE DEU_nodes` is different than `CREATE TABLE "DEU_nodes"`. In the first case the name is canonilcalized to lower case.

osm2pgsql quotes names in some places but not others. This is clearly a bug and will be fixed. Thanks for the report.

**Closed** 2021-02-26 14:12 UTC
