### ISSUE TITLE
--append is not working properly (data is deleted when it shouldn't)

### ISSUE THREAD

**Issue by timautin** [openstreetmap/osm2pgsql#938] opened 2019-07-10 11:24 UTC
Hello,

I'm setting up an OSM server that I want to keep synced hourly (could be minutely or daily if needed, it doesn't really matters). Everything seems to work (outputs of osmosis & osm2pgsql looks fine, osmosis does download the changes, and osm2pgsql does something to the database). But I have two problems:
- if I add / edit a feature on OSM iD, my local database does not get the update (openstreetmap.org did get the update)
- sometimes features are removed (for instance yesterday I lost the USA boundaries polygon, and today France & Spain boundaries are gone as well). They are removed from the DB, it's not a stylesheet problem

Here's the complete set of command I'm using:

1°) Database import

```
osm2pgsql \
    -d osm \
    --create --slim -G --hstore \
    -C 20000 \
    --number-processes 1 \
    --tag-transform-script ~/src/map-styles/openstreetmap-carto/openstreetmap-carto.lua \
    --style ~/src/map-styles/openstreetmap-carto/openstreetmap-carto.style \
    --flat-nodes /ssd/flat-nodes/osm.cache \
    <path/to/planet-osm.pbf>
```
The process took ~24h, and created a 719GB database (with last week's planet PBF).

2°) Prepare sync (only once)

```
# Set the location
WORKOSM_DIR=~/osm-sync

# Get the PBF file timestamp
TIMESTAMP=$(osmium fileinfo <path/to/planet-osm.pbf> | grep osmosis_replication_timestamp= | cut -c 35-54)

YEAR=$(echo $TIMESTAMP | cut -c 1-4)
MONTH=$(echo $TIMESTAMP | cut -c 6-7)
DAY=$(echo $TIMESTAMP | cut -c 9-10)
HOUR=$(echo $TIMESTAMP | cut -c 12-13)

# Download the initial state.txt
wget "https://replicate-sequences.osm.mazdermind.de/?Y=$YEAR&m=$MONTH&d=$DAY&H=$HOUR&i=00&s=00&stream=hour" -O $WORKOSM_DIR/state.txt

# Create the config file
rm -f $WORKOSM_DIR/configuration.txt
osmosis --read-replication-interval-init workingDirectory=$WORKOSM_DIR

# Update the config file
sed -i 's!http:!https:!' $WORKOSM_DIR/configuration.txt
sed -i 's!minute!hour!' $WORKOSM_DIR/configuration.txt
```

3°) Continue to sync (this is called every hour with a CRON task)

```
# Set some variables
WORKOSM_DIR=~/osm-sync
OSM_CARTO_DIR=<path-to-openstreetmap-carto>
EXPIRE_FILE_NAME=expire-list.txt

# Download changes
osmosis \
    --read-replication-interval workingDirectory=$WORKOSM_DIR \
    --simplify-change \
    --write-xml-change $WORKOSM_DIR/tmp/osmChange.xml

# Apply the changes
osm2pgsql \
    --database gis \
    --append --slim --multi-geometry --hstore \
    --cache 3000 \
    --tag-transform-script $OSM_CARTO_DIR/openstreetmap-carto.lua \
    --style $OSM_CARTO_DIR/openstreetmap-carto.style \
    --flat-nodes /ssd/flat-nodes/osm.cache \
    --expire-tiles 10-20 \
    --expire-output $WORKOSM_DIR/tmp/$EXPIRE_FILE_NAME \
    --input-reader xml \
    $WORKOSM_DIR/tmp/osmChange.xml

# Expire tiles in [10-15]
render_expired \
    --tile-dir /hdd/tile-cache/mod_tile \
    --min-zoom=10 \
    --max-zoom=15 \
    --touch-from=10 \
    --socket /var/run/renderd.sock < $WORKOSM_DIR/tmp/$EXPIRE_FILE_NAME

# Delete tiles in [16-20]
render_expired \
    --tile-dir /hdd/tile-cache/mod_tile \
    --min-zoom=16 \
    --max-zoom=20 \
    --delete-from=16 \
    --socket /var/run/renderd.sock < $WORKOSM_DIR/tmp/$EXPIRE_FILE_NAME
```

Did I miss something, or could the feature deletion be a bug?

**Comment by timautin** [comment] 2019-07-14 09:53
Some more information:

- I have the same behavior using SomeoneElseOSM's script (https://github.com/SomeoneElseOSM/mod_tile/blob/zoom/openstreetmap-tiles-update-expire)
- I have the same behavior on 3 different servers

**Comment by lonvia** [comment] 2019-07-19 18:36
Please confirm that your osmosis state file ($WORKDIR/state.txt) contains the expected date.

If that is okay then it sounds like you don't have the location information anymore. Did you remove your flatnode file between import and updates?

**Comment by timautin** [comment] 2019-07-19 18:53
Hi @lonvia ,
Since then I reimported with --drop option, as I decided to do manually updates until I find a solution. I'm setting up a second server on which I'll retry, but it's not ready yet. The first one has to go to production shortly.
From memory, I did not remove the flatnode file, but I'll double check that. Also, I think the state.txt does contain the right information: the first time it contains the PBF timestamp, then it is incremented by the period (1 minute, hour or day).
I'll come back with more info once my dev server is ready.
Thanks for answering :)

**Comment by lonvia** [comment] 2019-09-30 15:24
Closing for now. Please reopen if you encounter the issue again and have confirmed that the state file and flatnode file are in a proper state.

**Comment by crnm21** [comment] 2020-01-24 11:41
I'm reopening this as I experience the exact same behaviour.

I have two tileservers running in parallel and both loose data during appends - but: not the same data. One looses polygon X while the other looses polygon Y. (Both update on the exact same times).

No postgresql errors logged. Osm2pgsql runs through without error.

System: Ubuntu 18.04. Postgresql 10, Postgis 2.4.3. (POSTGIS="2.4.3 r16312" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.3, released 2017/11/20" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER)

Im using osmupdate --day (from osmtools) with biweekly updates but experienced the same behaviour whilst using osmosis). osm2pgsql is using a flatnode file. I (other than timautin) don't use multi-geometry.

The problem exists with osm2pgsql 0.94.
Now I do testing on another server where I use osm2pgsql 1.2.0 with Libosmium 2.15.4 and Lua 5.2.4.
And I'm seeing the problem again. Again no postgresql errors, but some polygons go amiss (normally I see this with large polygons like big lakes, countries and the like but it may occur on smaller areas as well - those are just not as easily to be seen).
I've contacted timautin as well and he is still experiencing the same erratic behaviour while updating through --append.

The flatnode file is fine, the state.txt where fine as well when I used osmosis, with osmupdate I use Midnight UTC as a param with the last updates date.

Could you give me any hints on how to best debug this odd behaviour?

**Comment by crnm21** [comment] 2020-01-24 14:11
So, I looked a bit more into the db, in this case for one of the lakes that is missing in one of those servers:
The relation is there as expected (and no diffs between the relations across two servers) but the polygon is gone in one of the two servers.
So there is sth. weird going on in polygon building from relations but I don't see any osm2pgsql errors.

**Comment by lonvia** [comment] 2020-01-24 16:54
It would be helpful if you can provide a detailed example of such a disappearing relation that includes the following:

* the OSM id of the relation that disappears
* the diff file that caused it to disappear together with the exact parameters you used with osmupdate to create this particular diff (i.e. I'd need to know which original diff files where mangled together)
* the exact command line you used with osm2pgsql including all referenced lua scripts (a pointer to the exact version of openstreetmap-carto will do, if applicable)

Also, could you please clarify if you are running a full planet or extract and, if the latter is the case, which one.

**Comment by crnm21** [comment] 2020-01-27 15:17
Hi lonvia,

thanks for reopening this.
Looking for the old missing polygons does not help as I cannot declare the exact diff update when it happened.

So I've just set up a test server again that will log all operations and diffs, so it will take some days until I may find new missing polygons but will have the data at hand to find the reason for lost polygons.

This is the initial import command line I'm using:

`sudo -u ${tileuser} osm2pgsql --slim -d ${dbname} --number-processes 8 --hstore --flat-nodes=/path/to/flatnodes.bin -C 64000 --style /path/to/openstreetmap-carto-4.24.1/openstreetmap-carto.style --tag-transform-script /path/to/openstreetmap-carto-4.24.1/openstreetmap-carto.lua /path/to/planet-200113.osm.pbf`

The import went thru without problems. I'm not using multi-geometry.

This following command line will be used for updates (date for first import, timestamp of planet-20113.osm.pbf is "2020-01-13T00:59:59Z", I'm going back one day.)

`osmupdate --day 2020-01-12T00:00:00Z $tmpfile && sudo -u ${tileuser} osm2pgsql --append --slim -d ${dbname} --number-processes 6 -C 64000 --hstore --flat-nodes=/path/to/flatnodes.bin --style /path/to/openstreetmap-carto-4.24.1/openstreetmap-carto.style --tag-transform-script /path/to/openstreetmap-carto-4.24.1/openstreetmap-carto.lua -e 6-19 -o $expirefile $tmpfile`

I'm using the normal openstreetmap-carto mapnik standard style in Version 4.24.1., so the Lua script can be found at [https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/lua/openstreetmap-carto.lua](https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/lua/openstreetmap-carto.lua). LuaJIT is not used.

**Comment by crnm21** [comment] 2020-03-27 09:26
So I did one of the biweekly updates again this night and maybe found a probable reason for the problem.

I do fetch the data each second friday at 1:15 UTC with

`osmupdate --day $lastrundate $tmpfile --kepp-tempfiles` where `$lastrundate` ist the date of the lastrun, in todays case it would be 2020-03-13T00:00:00Z as it did last run at Friday 13th of March at 1:15 UTC.

Now this is the list of tempfiles I got (I started the copied list some days earlier than this times update run):

```-rw-r--r--  1 [osmuser] [osmuser]   83 Mar  6 00:06 temp.d000002732.txt
-rw-r--r--  1 [osmuser] [osmuser]  85M Mar  7 00:06 temp.d000002733.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar  7 00:06 temp.d000002733.txt
-rw-r--r--  1 [osmuser] [osmuser]  64M Mar  8 00:06 temp.d000002734.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar  8 00:06 temp.d000002734.txt
-rw-r--r--  1 [osmuser] [osmuser]  76M Mar  9 00:06 temp.d000002735.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar  9 00:06 temp.d000002735.txt
-rw-r--r--  1 [osmuser] [osmuser]  94M Mar 10 00:06 temp.d000002736.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 10 00:06 temp.d000002736.txt
-rw-r--r--  1 [osmuser] [osmuser]  76M Mar 11 00:06 temp.d000002737.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 11 00:06 temp.d000002737.txt
-rw-r--r--  1 [osmuser] [osmuser]  93M Mar 12 00:06 temp.d000002738.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 12 00:06 temp.d000002738.txt
-rw-r--r--  1 [osmuser] [osmuser]  95M Mar 13 00:06 temp.d000002739.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 14 00:07 temp.d000002740.txt
-rw-r--r--  1 [osmuser] [osmuser]  72M Mar 15 00:06 temp.d000002741.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 15 00:06 temp.d000002741.txt
-rw-r--r--  1 [osmuser] [osmuser]  68M Mar 16 00:06 temp.d000002742.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 16 00:06 temp.d000002742.txt
-rw-r--r--  1 [osmuser] [osmuser]  92M Mar 17 00:07 temp.d000002743.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 17 00:07 temp.d000002743.txt
-rw-r--r--  1 [osmuser] [osmuser]  88M Mar 18 00:06 temp.d000002744.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 18 00:06 temp.d000002744.txt
-rw-r--r--  1 [osmuser] [osmuser]  88M Mar 19 00:07 temp.d000002745.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 19 00:07 temp.d000002745.txt
-rw-r--r--  1 [osmuser] [osmuser]  95M Mar 20 00:07 temp.d000002746.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 20 00:07 temp.d000002746.txt
-rw-r--r--  1 [osmuser] [osmuser]  94M Mar 21 00:06 temp.d000002747.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 21 00:06 temp.d000002747.txt
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 22 00:06 temp.d000002748.txt
-rw-r--r--  1 [osmuser] [osmuser]  88M Mar 23 00:06 temp.d000002749.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 23 00:06 temp.d000002749.txt
-rw-r--r--  1 [osmuser] [osmuser] 100M Mar 24 00:07 temp.d000002750.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 24 00:07 temp.d000002750.txt
-rw-r--r--  1 [osmuser] [osmuser]  89M Mar 25 00:06 temp.d000002751.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 25 00:06 temp.d000002751.txt
-rw-r--r--  1 [osmuser] [osmuser]  85M Mar 26 00:07 temp.d000002752.osc.gz
-rw-r--r--  1 [osmuser] [osmuser]   83 Mar 26 00:07 temp.d000002752.txt
-rw-r--r--  1 [osmuser] [osmuser]  96M Mar 27 00:06 temp.d000002753.osc.gz```

As you can see, the 2739.txt from March 13th is missing
as well as the 2740.osc.gz from March 14th.
So it does look as if I miss a day the way I'm doing it.
But I don't get why this is happening.

a) could I solve this by updating every two weeks but setting the update-from date to 15 days ago?

b) could I repair this by doing the update to the db again but this time running the last 15 days instead of the last 14?


(Also, as a sidenote, I had osm2gsql producing an error last time about not being able to close the zip at the end but I thought that is hopefully not important as it being the last step of cleaning up the operation - or am I wrong here?).

**Comment by lonvia** [comment] 2020-03-31 17:41
You never should do updates by date. Always continue them according to the sequence id. No idea how this works with osmupdate. I usually use pyosmium which does all the handling of sequence numbers for you, see [this section in its manual](https://docs.osmcode.org/pyosmium/latest/updating_osm_data.html#creating-change-files-for-updating-databases).

This clearly isn't a problem with osm2pgsql but with your update process, so closing the issue.

**Closed by lonvia** 2020-03-31 17:41 UTC
