### ISSUE TITLE
error during import is out of range for type integer

### ISSUE THREAD

**Issue by remyleone** [openstreetmap/osm2pgsql#1434] opened 2021-03-20 21:18 UTC
Hello I stumble upon the following problem while trying to do <https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/>

```
$ PGSSLMODE=disable  osm2pgsql --password --host 1.2.3.4 --username admin --port 42 -d gis --create --slim -G --hstore --tag-transform-script ~/workspace/openstreetmap-carto/openstreetmap-carto.lua -C 2500 --number-processes 1 -S ~/workspace/openstreetmap-carto/openstreetmap-carto.style azerbaijan-latest.osm.pbf
2021-03-20 22:09:26  osm2pgsql version 1.4.1
Password:
2021-03-20 22:09:27  Database version: 12.5 (Debian 12.5-1.pgdg100+1)
2021-03-20 22:09:27  PostGIS version: 3.1
2021-03-20 22:09:27  Node-cache: cache=2500MB, maxblocks=40000*65536, allocation method=11
2021-03-20 22:09:28  Setting up table 'planet_osm_point'
2021-03-20 22:09:28  Setting up table 'planet_osm_line'
2021-03-20 22:09:28  Setting up table 'planet_osm_polygon'
2021-03-20 22:09:28  Setting up table 'planet_osm_roads'
Processing: Node(1000k 1000.0k/s) Way(0k 0.00k/s) Relation(0 0.0/s)2021-03-20 22:09:40  ERROR: DB copy thread failed: Ending COPY mode for 'planet_osm_nodes' failed: ERROR:  value "4842224254" is out of range for type integer
CONTEXT:  COPY planet_osm_nodes, line 441664, column lon: "4842224254"
.
```

**Comment by SomeoneElseOSM** [comment] 2021-03-20 21:22
Could you provide a bit of information about the architecture in use here?

**Comment by remyleone** [comment] 2021-03-20 22:08
If you are talking about CPU architecture, I'm using x86_64 on both the client (macos) and the postgis server (Debian 12.5)

**Comment by lonvia** [comment] 2021-03-21 09:06
Works fine here with a azerbaijan-latest.osm.pbf from Geofabrik from today. Can you please repeat the import with a local database to check if the problem is with your remote connection.

**Comment by joto** [comment] 2021-04-29 15:43
Closing as not reproducible. Please reopen @remyleone if you can reproduce this reliably locally. We'll need the exact file then you tried this with.

**Closed by joto** 2021-04-29 15:43 UTC
