### ISSUE TITLE
Update stuck waiting for postgresql "COPY ... FROM STDIN" to finish

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/osm2pgsql#1273] opened 2020-09-17 18:13 UTC
* psql (PostgreSQL) 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1)
* osm2pgsql version 1.3.0, Compiled using the following library versions: Libosmium 2.15.6. Lua support not included
* I verified in `pg_settings` that `jit=off` and `jit_above_cost=-1`

Running any daily Nominatim update gets stuck with `COPY "place" FROM STDIN` Postgresql query running and CPU core at 100% and no disk activity. The `osmosischange.osc` file is about 1.2GB but no change in 20 hours.

Nominatim's `./utils/update.php --import-osmosis --index-instances 30` executes `osm2pgsql --hstore --latlong --append --slim --number-processes 1 --cache 2000 --output gazetteer --style /srv/nominatim/Nominatim/settings/import-full.style --database nominatim --port 5432 --flat-nodes /ssd/flatnode.file`

Output to STDOUT stops after
```
[2020-09-16 22:37:20] Node stats: total(4185341), max(7899006801) in 105s
[2020-09-16 22:37:20] Way stats: total(557522), max(846592436) in 75s
[2020-09-16 22:37:20] Relation stats: total(11637), max(11610493) in 6785s
```

Attached the Postgresql process list and stack trace of the osm2pgsql process. Let me know if there's anything else I can provide.

[postgresql_process_list.txt](https://github.com/openstreetmap/osm2pgsql/files/5241007/postgresql_process_list.txt)
[stack_trace.txt](https://github.com/openstreetmap/osm2pgsql/files/5241011/stack_trace.txt)

Seeing the issue on two servers. Both fresh installed with last week's planet pdf dump imported.

I kind of expect that you advise me to run use `--index-instances 1` instead. But maybe it's a threading issue that can be addressed.

**Comment by mmd-osm** [comment] 2020-09-18 06:21
Is you db running on another host? Network issues? The only active thread is currently waiting on some response from postgres:

```
TID 1562673:
#0  0x00007f1f8d04c96f __poll
#1  0x00007f1f8d7ff340
#2  0x00007f1f8d7ff4bc
#3  0x00007f1f8d7fd20c PQgetResult
#4  0x000055a5d6e11e3f pg_conn_t::end_copy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
#5  0x000055a5d6e21943 db_copy_thread_t::thread_t::finish_copy()
#6  0x000055a5d6e22f36 db_copy_thread_t::thread_t::write_to_db(db_cmd_copy_t*)
#7  0x000055a5d6e2381b db_copy_thread_t::thread_t::operator()()
#8  0x00007f1f8d369cb4
```

**Comment by lonvia** [comment] 2020-09-18 08:30
This has definitely nothing to do with `--index-instances` because osm2pgsql is hard-wired to use only 1 process for updates. You can see that in the command line you posted.

We don't do anything fancy at the point where it hangs. osm2pgsql simply waits for COPY to finish. The problem with the gazetteer output is that there is a complicated set of triggers running in the background which might have a bug itself or trigger a Postgresql bug in the background. But we'd need a reproducable test case (preferably with a diff that is significantly smaller than 1 GB) to debug that.

What is the output of `SELECT * FROM pg_stat_activity`?

**Comment by mtmail** [comment] 2020-09-18 22:59
Database is local on NVMe drive, connection via socket.

The update continued after 28 hours, unclear what or why caused it to continue. Then the next 3 updates took 2-3 hours. Now on the 4th update (1.1GB *.osc file) it hangs again for 12 hours.

Full pg stat output, I hope it's readable.
[full_pg_stat_activity.txt](https://github.com/openstreetmap/osm2pgsql/files/5248547/full_pg_stat_activity.txt)

Stack trace of the postgresql process taking 100% CPU
[postgresql-process-stack-trace.txt](https://github.com/openstreetmap/osm2pgsql/files/5248560/postgresql-process-stack-trace.txt)

I agree it looks like something is waiting for a COPY to finish (`iotop` reports no reading). And in Postgresql it runs a read on the file.

**Comment by mmd-osm** [comment] 2020-09-19 07:05
The PostgreSQL stack trace seems to indicate that it’s calling an insert trigger which is calling another insert trigger that is currently doing an index scan. I didn’t spot anything in the traces that would reveal the corresponding expensive statement(s).

**Comment by lonvia** [comment] 2020-09-19 14:01
That sounds like an issue with the query planner again. It's a pain to debug inside the triggers. In any case, it is a Nominatim issue, so moving the issue over there.

**Comment by lonvia** [comment] 2020-09-22 14:58
I've confirmed that this is an issue with the query planner inside the Nominatim triggers. https://github.com/osm-search/Nominatim/pull/1970 addresses the problem. Closing here.

**Closed by lonvia** 2020-09-22 14:58 UTC
