### ISSUE TITLE
Command osm2pgsql --append --slim gives ERROR:  duplicate key value violates unique constraint "planet_osm_rels_pkey"

### ISSUE THREAD

**Issue by LXSysadmin** [openstreetmap/osm2pgsql#769] opened 2017-06-28 08:46 UTC
I have used manual https://switch2osm.org/serving-tiles/building-a-tile-server-from-packages/ for Ubuntu 14.04 and have imported ¨europe-latest.osm.pbf¨ with command osm2pgsql --slim -C 24500 --number-processes 8 europe-latest.osm.pbf. Now i want to add USA map, i have downloaded ¨south-america-latest.osm.pbf¨ and executed command osm2pgsql --append --slim -C 24500 --number-processes 8 south-america-latest.osm.pbf BUT i get error: 
COPY_END for COPY planet_osm_rels FROM STDIN;
 failed: ERROR:  duplicate key value violates unique constraint "planet_osm_rels_pkey"
DETAIL:  Key (id)=(2668952) already exists.
CONTEXT:  COPY planet_osm_rels, line 4301

What could be the problem?

**Comment by pnorman** [comment] 2017-06-28 20:21
duplicate of #16

**Closed by pnorman** 2017-06-28 20:21 UTC
