### ISSUE TITLE
Wrong polygon generation (overfitting) with closed ways

### ISSUE THREAD

**Issue by sfkeller** [openstreetmap/osm2pgsql#304] opened 2015-02-22 11:37 UTC
osm2pgsql is incorrectly (and unintentionally) bulding polygons out of single closed ways (e.g. junction=roundabouts) when they are additionally part of a relation (disregarding if relation is multipolygon or a (bus) line).

Look at these two roundabouts (both single closed way):
1. http://www.openstreetmap.org/way/24932843
   ...
   Part of
     Relation Bus 992: Rapperswil - Jona Bahnhof (2691985)
     ...
2. http://www.openstreetmap.org/way/217996619
   ...
   Part of
     Relation Bus 992: Rapperswil - Jona Bahnhof (2691985)
     Relation 2887574 (as outer)
     ...

BTW: For Switzerland there are currently ~2729 in table osm_polygon (where they don't belong) and ~1245 roundabouts correctly generated into table osm_line. And the intersection of roundabouts in both tables is currently 1 single relation. Tested with: "SELECT osm_id FROM osm_line WHERE junction='roundabout' AND osm_id IN (SELECT osm_id FROM osm_polygon WHERE junction='roundabout')".

**Comment by lonvia** [comment] 2015-02-22 12:15
I still cannot reproduce the error. Tested with the latest version of osm2pgsql as follows:
~~~
me@local> wget -O junction-with-rel.osm http://www.openstreetmap.org/api/0.6/relation/2691985/full
me@local> ./osm2pgsql -S default.style -s junction-with-rel.osm
me@local> pgsql gis
gis=# select osm_id from planet_osm_polygon ;
 osm_id 
--------
(0 rows)
gis=# select osm_id from planet_osm_line where junction = 'roundabout';
  osm_id   
-----------
  24932843
 217996619
 308599206
 136920568
  24932882
 308599205
  28301879
 308599204
(8 rows)
~~~

Which version of osm2pgsql are you using and what is the exact command line you use for the import?

**Comment by sfkeller** [comment] 2015-02-22 16:18
Yes, newer osm2pgsql versions seem to work! I have to lookup which version we're using in production - but it won't be the latest for sure since it's debian :-(.

I now tested it on Windows "osm2pgsql SVN version 0.83.0 (64bit id space)" and Switzerland (thanks to Geofabrik downloads). I'm getting 3635 roundabouts in planet_osm_line which comes close to what I expect.

Looking at planet_osm_polygon still returns some rows:

    psql -h localhost -p 5433 -U postgres -c "SELECT osm_id, ST_AsText(way), tags \
        FROM planet_osm_polygon WHERE junction='roundabout'" gis
Namely these 6 rows: -3267310, -1700414, -2442909, -1658589, -2887574, 136646975.
First 5 relations (all negative) have "type=multipolygon" which is incorrect in the data.

One other use case is way http://www.openstreetmap.org/way/136646975 being part of http://www.openstreetmap.org/relation/319761, The relation contains no "type=multipolygon" but way 136646975 contains "landuse=grass". 

This landuse should be deleted or "area=no" added (and needs an explanation in the Wiki page http://wiki.osm.org/wiki/Tag:junction%3Droundabout ).

**Comment by simonpoole** [comment] 2015-02-23 07:14
I don't believe http://www.openstreetmap.org/relation/319761 is "wrong" it is simply representing two objects with one OSM feature (which is completly ok), osm2pgsql should likely import it twice.

**Comment by mboeringa** [comment] 2015-02-24 20:58
> This landuse should be deleted or "area=no" added (and needs an explanation in the Wiki page http://wiki.osm.org/wiki/Tag:junction%3Droundabout ).

Agree, this is just plain bad tagging. How is software ever going to make sense of this, unless every tagging combination is hard-coded, which seems undesirable, not even taking into account being virtually - and practically - impossible with the plethora of options in the free tagging scheme of OSM...

Like you suggest, remove **landuse=grass**, and add it to a separate closed way or multipolygon object. Then add **area=no** to the remaining junction line object.

Sometimes I wonder if all OSM (editor) applications shouldn't drop support for simple closed ways all together, and only support multipolygons as area features. It would at least take away some of the ambiguity associated with simple closed loops.

**Comment by pnorman** [comment] 2015-02-27 19:59
The reported issue is resolved in the latest version, so I'm closing this issue.

If someone feels that an OSM object should convert to **both** a `LINESTRING` and a `POLYGON` they can open a new issue.

**Comment by SomeoneElseOSM** [comment] 2015-03-17 10:03
I'm not sure if this is similar or not, but while http://www.openstreetmap.org/relation/4672722 existed the roundabout consisting of ways such as http://www.openstreetmap.org/way/33181751 didn't render on OSM-carto, humanitarian or my local database.  In my case it was due to the constituent way not being in the database:

psql -c "select osm_id from planet_osm_roads where osm_id = '33181751'" gis
 osm_id
--------
(0 rows)

I'm running "osm2pgsql SVN version 0.85.0 (64bit id space)" which would of course not contain any fix from 18 days ago, but for info @simonpoole sees a similar thing with 0.87.2-dev .

**Comment by pnorman** [comment] 2015-03-18 06:58
> I'm not sure if this is similar or not, but while http://www.openstreetmap.org/relation/4672722 existed the roundabout consisting of ways such as http://www.openstreetmap.org/way/33181751 didn't render on OSM-carto, humanitarian or my local database. In my case it was due to the constituent way not being in the database:

What you describe is correct behavior - the way gets converted to a POLYGON instead of a LINESTRING, which is the expected behavior for multipolygons.

**Comment by lonvia** [comment] 2015-03-21 09:05
The relation should go in planet_osm_polygon, that is correct. What is not correct is that the enclosing ways are deleted. They should remain ways of their own because they are not polygon features. This is a case of wrong old-style multipolygon handling.

**Comment by lonvia** [comment] 2019-10-21 21:11
Old-style multipolygons are no longer supported, so time to close this.

**Closed by lonvia** 2019-10-21 21:11 UTC
Labels: multipolygon
