### ISSUE TITLE
Large object id triggers segfault

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osm2pgsql#965] opened 2019-10-29 18:08 UTC
While debugging some other issue, I noticed that particularly large object ids trigger a segfault in `node_ram_cache::set_dense(long, osmium::Location const&)` at node-ram-cache.cpp:141 (tested on 8d9087f1111f4a062158e8e6b10bfbceed90899b ). I'd rather expect an error message here stating that the object id is too large.

This is not really urgent in any way, as it might only affect people mixing OSM with some other data. I thought I'd raise it anyway, as segfaults are generally not so nice.

Test example: (`osm2pgsql -d osm  tesfile.osm`).

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' generator='JOSM'>
  <node id='540000000001' timestamp='2015-01-01T00:00:00Z' uid='1' user='3' version='1' changeset='10' lat='50' lon='7'/>
</osm>
```

**Comment by lonvia** [comment] 2019-10-29 19:54
Duplicate of #290. Leaving this one open though as it has a better description.

**Comment by vincnetas** [comment] 2020-01-06 14:48
Why is this "Duplicate of #290" But in #290 it says that "Closing in favour of #965."
Looks like cyclical reference.
And yes, came here because having Segfaults when importing OSM data with lua filter.

**Comment by joto** [comment] 2020-01-06 15:09
@vincnetas It is the nature of duplicates, that if one is the duplicate of the other, the other is a duplicate of the first. Doesn't matter which way you look at it. The other one is closed and this one is open. So all is in order.

**Comment by jochenhebbrecht** [comment] 2021-02-22 15:57
Hi,

I'm currently using `osm2pgsql` version `1.4.0` to load a PBF file which has OSM node ids > 10.000.000.000.000.
It fails with:
```
# osm2pgsql -H localhost -P 5432 -U postgres -W /tmp/world.osm.pbf
2021-02-22 15:54:10  osm2pgsql version 1.4.0
Password:
2021-02-22 15:54:13  Database version: 9.5.16
2021-02-22 15:54:13  Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=3
2021-02-22 15:54:13  Setting up table 'planet_osm_point'
2021-02-22 15:54:13  Setting up table 'planet_osm_line'
2021-02-22 15:54:13  Setting up table 'planet_osm_polygon'
2021-02-22 15:54:13  Setting up table 'planet_osm_roads'
Segmentation fault (core dumped)
```
Is the fix described in #290 already in `1.4.0`?

Jochen

**Comment by joto** [comment] 2021-02-23 08:01
There is no fix in #290. This is still open.

This is one of those cases where it is rather unlikely that we will spend time on. These large objects ids are not in OSM data so it doesn't affect most users. The large IDs are usually the result of somebody creating "fake" OSM data, often from proprietary data. May I suggest you fund the development of osm2pgsql if you do this kind of thing, there is a better chance we'll get this fixed then.

**Comment by jochenhebbrecht** [comment] 2021-02-23 08:37
Thanks, no worries. I see I misunderstood the comment in #290.

Do I get it correctly that `osm2pgsql` currently supports object ids up to 32 bits? Being defined over here https://github.com/openstreetmap/osm2pgsql/blob/master/src/middle-ram.hpp#L48?

And only if we really want to make it work for us, we could change `32` to `44` for example? Theoretically, that should work, yes? ( I'm not saying that we're going to do this :-D )

**Comment by lonvia** [comment] 2021-02-23 08:55
The suggested change in #290 concerns way IDs. The hard coded limit for nodes is 2^36 if I read the (code in middle-ram-cache)[https://github.com/openstreetmap/osm2pgsql/blob/master/src/node-ram-cache.hpp#L87] correctly. Note that increasing this number increases RAM use significantly.

**Comment by jochenhebbrecht** [comment] 2021-02-23 08:58
Thanks @lonvia . That's a great reply. All clear to me now :-)

**Comment by joto** [comment] 2021-05-17 15:06
The offending code was removed in #1500. Closing here.

**Closed by joto** 2021-05-17 15:06 UTC
