### ISSUE TITLE
1.5.0 not all objects found in planet_osm_line/polygon in their full form

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/osm2pgsql#1540] opened 2021-07-18 19:39 UTC
```
$ osm2pgsql --version
2021-07-18 22:35:52  osm2pgsql version 1.5.0
Build: None
Compiled using the following library versions:
Libosmium 2.17.0
Proj [API 4] Rel. 7.2.1, January 1st, 2021
Lua 5.3.3


$ osm2pgsql --style basemap/osm2pgsql_styles/default.style --number-processes 32 --hstore-all --hstore-add-index --create data/planet-latest-updated.osm.pbf
```

Non-slim import. Geometries found not in their full form:

![image](https://user-images.githubusercontent.com/810638/126080035-9aadd383-af83-47ae-8788-988f638480ed.png)

Green lines - same dump's roads imported via osmium

Red lines are "highway is not null" from planet_osm_line
Yellow "building is not null" from planet_osm_polygon

Spot is https://www.openstreetmap.org/#map=16/37.7803/-122.4683 but the issue is worldwide.

**Comment by Komzpa** [comment] 2021-07-18 20:21
One sample is way 852278221. It is absent in osm2pgsql import table and present in generated via other means.

**Comment by joto** [comment] 2021-07-18 20:32
I am not sure I understand you correctly. I don't see any green lines in your image? What's this to do with osmium? Do I understand you correctly that some roads and some buildings that you would expect to be in the data aren't? So presumably some geometries were not built? The background map shown in the image is the normal OSM map? Does this only happen on planet import or also if you import a smaller extract of the affected areas? Can you see any patterns in the data that could explain what's imported and what not? What's in `basemap/osm2pgsql_styles/default.style`?

**Comment by joto** [comment] 2021-07-18 21:30
Which PostgreSQL version are you using?

**Comment by pnorman** [comment] 2021-07-19 01:38
I tried replicating it with the way from the API and `osm2pgsql --number-processes 32 --hstore-all --hstore-add-index -d osm2pgsqltest -S default.style 852278221.xml`. When I did `SELECT * FROM planet_osm_line;` I got the object.

Can you provide a test case?

**Comment by Komzpa** [comment] 2021-07-19 05:49
Green lines: sorry, I attached a screenshot that did not have them. 

Osmium: we have a second pipeline processing the same dump via `osmium export -f pg` but still need osm2pgsql for some legacy software stack.

Yes, buildings, roads and other objects present in dump are corrupted in import.

The background is normal map.

Thanks to @pnorman for replication attempt. It looks like either our setups are different or it only affects planet.

I see a pattern that often objects that share vertices get corrupted, and there is some locality in corruption in imported regions - node ID ranges? Not a distinctive range.

basemap/osm2pgsql_styles/default.style is vanilla one.

I have re-imported the planet overnight via `osm2pgsql --style basemap/osm2pgsql_styles/default.style --number-processes 32 --hstore-all --flat-nodes data/planet-latest-updated-flat-nodes --slim --drop --create data/planet-latest-updated.osm.pbf ` and can find way 852278221 in planet_osm_line.

Versions:
```
08:36:28 [gis] > select postgis_full_version();
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                      postgis_full_version                                                                                                                      │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ POSTGIS="3.2.0dev 3.1.0rc1-325-g13634f91f" [EXTENSION] PGSQL="130" GEOS="3.10.0dev-CAPI-1.15.0" SFCGAL="1.3.8" PROJ="7.2.1" GDAL="GDAL 3.2.2, released 2021/03/05" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY RASTER │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(1 row)

Time: 1598,717 ms (00:01,599)
08:37:24 [gis] > select version();
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                           version                                                           │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg21.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, 64-bit │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(1 row)

Time: 0,447 ms
```

**Comment by pnorman** [comment] 2021-07-19 06:25
How is `planet-latest-updated.osm.pbf` created? Is it ordered? Does this happen with `--number-processes 1`?

**Comment by Komzpa** [comment] 2021-07-19 08:30
planet-latest-updated.osm.pbf is created via `osmium apply-changes` of a diff recived via `pyosmium-get-changes`. I did not check --number-processes 1.

**Comment by joto** [comment] 2021-07-19 09:33
I can reproduce this now in a way: I see that some nodes are missing in the node cache when I run osm2pgsql on a planet file. Those nodes are in the planet, so they should be in the cache but aren't. This can easily explain missing features, because features with broken geometries are simply ignored by osm2pgsql.

Problem is: I have tried several extracts and in thoses cases osm2pgsql seems to run just fine. This happens *only* with the planet file. It seems not to be tied to the location or ids of those nodes, but to the size of the input file. This makes debugging this somewhat difficult, because I might have to wait a few hours for a test run to complete.

**Comment by mboeringa** [comment] 2021-07-19 21:34
> I can reproduce this now in a way: I see that some nodes are missing in the node cache when I run osm2pgsql on a planet file. Those nodes are in the planet, so they should be in the cache but aren't. This can easily explain missing features, because features with broken geometries are simply ignored by osm2pgsql.

@joto: Based on your description, does this mean that if "--cache=0", this issue may not occur?

I am asking, because as you know, I have been experimenting recently as well with osm2pgsql v1.5.0 and osm2pgsql flex output with both official OSM planet files, and Facebook Daylight. However, during a few of these imports (some with cache and others "--cache=0"), I noticed missing polygons. I first blamed this on a possible issue in either some of my own post-import processing code, or an issue with how I used osmium to merge Facebook planet with Microsoft ML building and boundaries as offered by Facebook. 

But now I am wondering if I didn't run into the same issue, as the last run that did seem OK, used "--cache=0".

**Comment by joto** [comment] 2021-07-20 07:52
@Komzpa I have pushed a fix in #1541. Can you check whether this fixes the problem?

@mboeringa This bug only appears when the RAM cache is used and has more than something like 1 billion entries, so only for very large extracts or the planet file (and very large `--cache` settings when in slim mode).

**Comment by mboeringa** [comment] 2021-07-20 08:00
> @mboeringa This bug only appears when the RAM cache is used and has more than something like 1 billion entries, so only for very large extracts or the planet file (and very large `--cache` settings when in slim mode).

That would definitely explain the behavior and issue that I was seeing, and that I blamed on an issue in my own ongoing code development work. I did not witness the same issue with much smaller (Italy & Netherlands) extracts of Geofabrik.

I'll see if I can do a full planet test run with the latest version as well.

**Comment by Komzpa** [comment] 2021-07-20 08:06
> I have pushed a fix in #1541. Can you check whether this fixes the problem?

I will not be able to experiment before weekend. If @mboeringa can have a run earlier, please do!

**Comment by mboeringa** [comment] 2021-07-20 08:14
> I will not be able to experiment before weekend. If @mboeringa can have a run earlier, please do!

I realized though, that I have no idea how to update my local repository copy on Ubuntu to a non-merged pull request like this one. The few times I have build osm2pgsql, was always from master.

@Komzpa , do you possibly have some instructions for me on how to do that on Ubuntu and build a new copy of osm2pgsql with these latest changes?

**Comment by mboeringa** [comment] 2021-07-20 08:21
Ok, I see it is already merged now, so I'll have a go at it and see if I can re-compile my copy and do a test run.

**Comment by mboeringa** [comment] 2021-07-21 11:24
@joto,

I am running into an issue with a **bad_alloc** with the data I am trying to process (67.3 GB Facebook Daylight). 

I am currently using a custom version of Paul's "flex version" of the openstreetmap-carto style (https://github.com/gravitystorm/openstreetmap-carto/pull/4431).

The main difference is that I de-activated second stage flex processing as needed for the admin boundaries stuff, and also the creation of the additional 'planet_osm_admin'/'planet_osm_transport_line'/'planet_osm_transport_polygon'/'planet_osm_route' tables, to reduce overhead in processing and RAM usage. Only the minimum 'planet_osm_point/line/polygon' tables will be created instead. 

- Note that I have used this custom version without issues on smaller extracts (tested multiple times)!
- Note also that I successfully imported the same extract using osm2pgsql v1.5.0 **before the fix** and using this style, _but with "--cache=0"_!

Now I initially ran out of RAM (110 GB available to Ubuntu VM), and the process got "killed" by Ubuntu. I than increased my swap space to 150 GB, and then get the "bad_alloc" message during way processing (tested twice).

Could this still be a memory issue? I would have expected the process to be killed when out of virtual memory, like the first time, but that clearly didn't happen.

Any other suggestions or comments regarding this specific error?

![afbeelding](https://user-images.githubusercontent.com/7635726/126479078-6cb34689-337e-4cb1-b2b5-98cfb7d9f144.png)

**Comment by joto** [comment] 2021-07-21 12:18
@mboeringa Please keep discussion to the one issue on hand. Otherwise this becomes a jumbled mess and nobody knows any more what we are talking about. Introducing a totally different and hugely complex case doesn't help. Also: This is an issue tracker for reporting and finding bugs in osm2pgsql not a general "I am doing somebody complex please help me" help line. So unless you have reason to believe that osm2pgsql does something wrong, this is not the place to discuss your issues.

**Comment by mboeringa** [comment] 2021-07-21 12:40
> Introducing a totally different and hugely complex case doesn't help. Also: This is an issue tracker for reporting and finding bugs in osm2pgsql not a general "I am doing somebody complex please help me" help line.

@joto, this isn't a "complex case". This is just a flex style! 

With all respect, if from now on you consider even referencing use of flex in the issue tracker as "doing something hugely complex" not-worth-commenting-on, we might as well abandon the flex output... _I just wanted to roughly describe what I am working with._

I am pretty sure the issue isn't with flex style, and as said, I have de-activated those parts involved in stage 2 processing.

Nonetheless, I will make an attempt using the osm2pgsql default style and using **pgsql** output, as @Komzpa noted and used in his first post. Let's see what happens then.

I would still appreciate it though, if you could comment on the "bad_alloc" error, and where it stems from. E.g. is this from osm2pgsql code, or a forwarded message from postgresql? 

And yes, I do have reason to believe that "osm2pgsql was doing something wrong here", based on similar results to what @Komzpa had of missing geometries in the planet import output.

**Comment by lonvia** [comment] 2021-07-21 12:53
@mboeringa This issue is about missing geometries. You are not helping at all by giving lengthy descriptions about memory issues. If you can test case where you have observed missing geometries before and can check if exactly these missing geometry issues are gone, then you are welcome to comment here. Anything else: open up a new discussion thread in the discussion sections. I'm going to hide this off-topic discussion now and will delete all further off-topic comments without notice.

**Comment by mboeringa** [comment] 2021-07-21 12:58
> If you can test case where you have observed missing geometries before and **can check if exactly these missing geometry issues are gone**, then you are welcome to comment here.

@lonvia. This is exactly what I attempted to do, and it seemed prudent to me to use the same configuration I used before (which also was flex output), so as to not introduce a new variable (switch to pgsql output as I will now do to match @Komzpa case).

**Comment by mboeringa** [comment] 2021-07-22 07:50
@Komzpa . My VM just got stuck in unrecoverable state, that I will need to restore from backup. So it will be up to you to test.

**Comment by joto** [comment] 2021-07-30 07:49
I believe this has been fixed in release 1.5.1. Please reopen if the issue persists.

**Closed by joto** 2021-07-30 07:49 UTC

**Comment by mboeringa** [comment] 2021-08-04 07:17
@joto and @Komzpa ,

Although slightly preliminary (I am still waiting on more tables to be generated), this image of DBeaver based on the v1.5.1 version of osm2pgsql, seems to indicate the latest version is fine. This was based on an import with a cache setting of 150 GB. In the buggy version, the whole of the Greenland icecap was missing as one obvious error. No such thing visible in this image of features tagged as **natural=glacier** in OpenStreetMap. Note that this is a generalized version of the data, so really small features below a certain threshold, do get discarded by the generalization processing and do not show up in the image:

![afbeelding](https://user-images.githubusercontent.com/7635726/128137650-80beae23-8f54-4a4d-927b-a93da67c2b73.png)

**Comment by mboeringa** [comment] 2021-08-05 07:37
The generalized forest layer looks OK as well. No large missing areas in e.g. Russia as I witnessed before:

![afbeelding](https://user-images.githubusercontent.com/7635726/128310691-1c65b913-804f-4d67-b217-f6a61e74ba1b.png)
