### ISSUE TITLE
osm2pgsql fails to create "osm_id" indexes on PostgreSQL 14

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1674] opened 2022-05-15 07:06 UTC
## What version of osm2pgsql are you using?

1.6.0 (1.3.0-580-g06d4013)

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 20.04.1 LTS, PostgreSQL 14.3, PostGIS 3.2

## Tell us something about your system

HP Z840 with dual Xeon E5-2680 v4, 256 GB RAM, 4x2TB NVMe

## What did you do exactly?

Import Planet using osm2pgsql in an empty database.

## What did you expect to happen?

**osm_id** column indexes being properly created during the import process, and before the DELETE taking place in flex processing during the **"There are X ways to reprocess"** processing stage.

## What did happen instead?

Despite the index statements being visible as "idle" sessions in pgAdmin, no indexes are actually being created in PostgreSQL 14 after a successful upgrade from PostgreSQL 13 to 14. This causes a significant delay in the processing of the subsequent DELETE statements issued by osm2pgsql as part of the **"There are X ways to reprocess"** processing stage. It takes hours to process all of the DELETE statements, with consistent high disk read activity, suggesting PostgreSQL is going over the entire table time and again in a full table scan.

Although I can no longer properly verify, since I upgraded my cluster, I have never seen such issues with PostgreSQL 13, and no huge delay was experienced on previous releases of PostgreSQL (The reprocessing ways stage in PostgreSQL 13 only took between 15-30 minutes max).

## What did you do to try analyzing the problem?

Reviewed osm2pgsql output and monitored database activity in pgAdmin:

![afbeelding](https://user-images.githubusercontent.com/7635726/168461331-bc484e0d-6ce5-4721-b3f3-20e10e6511fe.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/168461360-56c9faff-165c-4ce5-88ba-246e488ae249.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/168461367-d59e3f22-e6ff-4902-b179-e995e84c428c.png)

**Comment by mboeringa** [comment] 2022-05-15 07:40
Weird, I now noticed in pgAdmin that the "Location" property of the **pg_default** tablespace is empty after the upgrade from PostgreSQL 13 to 14. I have never seen this happens with previous upgrades. I wonder if this is a bug in the **pg_upgradecluster** command used to upgrade from 13 to 14? Since osm2pgsql uses the pg_default tablespace as input in the INDEX statements of the osm_id columns, the missing "Location" property is the likely cause of the failure to create them.

![afbeelding](https://user-images.githubusercontent.com/7635726/168462317-0207367c-3536-48e4-98a5-eb0859f14e91.png)

**Comment by mboeringa** [comment] 2022-05-15 13:47
I have now restarted the old PG13 cluster, and that shows the same empty "Location" field in pgAdmin, so this observation is likely insignificant and not relevant to the issue. I can also successfully import in the PG13 cluster, when using a small test dataset. 

The same when I use the PG14 cluster, it does finish, but processing is so quick that it is impossible to tell whether or not the intermediate "osm_id" column indexes were created or not. The final indexes on primary key and way are there though.

I did notice I had accidentally used an osm2pgsql flex style with 'public' schema as default instead of a custom schema when doing the large Planet import. I need to retry with a dedicated schema for the user and see if that fixes the issue.

**Comment by mboeringa** [comment] 2022-05-16 06:10
Setting a dedicated non-public schema also solved the missing **"osm_id"** column index problem for the Planet import, unfortunately, it doesn't seem to solve the performance problem in PG14.

I do see processing going on when watching the incoming DELETE statements send by osm2pgsql in pgAdmin. However, it is just terribly slow. Processing one batch of records as defined in one SQL statement, seems to take a minute or so.

The DELETE process initiated by "There are X ways to reprocess" processing step of osm2pgsql started at 2:11 AM, and is now 6 hours later still on-going... 

It is almost as if PostgreSQL still ignores the **"osm_id"** index...

**Comment by joto** [comment] 2022-05-16 07:51
Can you please post the exact command lines and any config files used? It would probably also help if you turned up logging in your PostgreSQL, so that you can see whether indexes were created or not. You can also run osm2pgsql with `--log-sql` which will show you exactly which SQL commands were issued (careful, can be a lot of output).

Note that indexes on the ids columns will only be created when using `--slim` mode or when using two-stage processing.

**Comment by mboeringa** [comment] 2022-05-18 07:51
@joto. The exact command line is one below. The latest version of the osm2pgsql 'flex' LUA style used is the one below in the zip. Do notice this style has a top configuration section with a 

`local db_schema = 'public'`

configuration setting that needs to be changed to the appropriate schema if a using a dedicated schema. I still need to verify it, but the separate issue of missing indexes seemed to occur with the schema set to public.

[openstreetmap-carto.zip](https://github.com/openstreetmap/osm2pgsql/files/8714129/openstreetmap-carto.zip)

![afbeelding](https://user-images.githubusercontent.com/7635726/168978751-ea5edca0-6e8d-43e2-942b-2797096e625d.png)

I have now also had a look at the postgresql logs. One particular thing I noticed, is that I see the DELETE statements of the **"There are X ways to reprocess"** processing step intermingled with continuously repeating COPY statements for the Line table. Note that these continuously emitted COPY statements already started at the **way** loading stage, so before the **"There are X ways to reprocess"** processing step.

Is this normal behavior? Strangely, I do not see these same SQL statements in pgAdmin, while I **do** see the DELETE statements in pgAdmin.

![afbeelding](https://user-images.githubusercontent.com/7635726/168984457-66b0e940-7bb0-4086-9d8b-170d12588109.png)

I have also had a closer look at the actual resource usage during the slow running **"There are X ways to reprocess"** processing step. As you can see from these image, PostgreSQL is only using a single core at 75%-100%, and iowait is negligible, so there appears to be at least no IO bottleneck:

![afbeelding](https://user-images.githubusercontent.com/7635726/168985197-dc050309-f786-4d33-90ad-899b1f1e89b2.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/168985771-e3379e3f-50a2-4751-acf2-12172c3afb9c.png)

**Comment by joto** [comment] 2022-05-18 10:06
You are posting a lot of detail that's not really relevant to the question of whether the index was created or not. If the index was not created when calling osm2pgsql with your commandline, than that's a bug. If the index was created than that's not a bug and we can't help you any further here. Sorry, but we are not wading through many screen shots to figure out why something might be slow on your specific system in your specifiy use case, that's just beyond what can be expected as a free service. Everything I am seeing here is consistent with what I would expect osm2pgsql to do.

**Comment by mboeringa** [comment] 2022-05-18 10:13
@joto 

I am actually suspecting a PG14 bug, not an osm2pgsql issue. But I am not yet sure, that is why I am digging deeper.

It baffles me to see such disinterest.

It is not normal if a simple upgrade from PG13 to 14 lengthens the time for this specific processing stage from 15-30 minutes to 6 hours, without any changes to the osm2pgsql Lua flex style file.

And as I already wrote, I **DO** see the indexes being generated (at least with a non-public schema), so the indexes issue can be ignored for now.

**Comment by lonvia** [comment] 2022-05-18 12:06
So the bug report about indexes is wrong? Then I'm closing this issue. This issue has side-tracked too much to make it possible find any actionable information.

@mboeringa You are welcome to continue speculations in the discussion section. Please open only issues if you have found a bug in osm2pgsql and can give precise steps to reproduce the situation. Preferably one that does not involve an overly complex flex configuration or a full planet import.

**Closed by lonvia** 2022-05-18 12:06 UTC

**Comment by mboeringa** [comment] 2022-05-19 16:52
@joto 

If I need to determine if this is a PostgreSQL issue or osm2pgsql one, it would be helpful if you could answer two minor questions. These are probably easily answered, as likely not requiring more than a superficial look at the osm2pgsql code, or maybe you can even answer them from the top of your head knowing the code base so well:

- Does osm2pgsql run ANALYZE directly after creating the indexes on the "osm_id" columns, so the PostgreSQL planner is garantueed to know of their existence and usefulness before osm2pgsql starts emitting the DELETE statements for the "There are X ways to reprocess" stage?
- How many "osm_id" values are included in each batch as defined by the DELETE's "IN" clause? 100, 1000, 10k? If I need to simulate what osm2pgsql does in order to reproduce the issue in PostgreSQL without involvement of osm2pgsql, this is vital information.

**Comment by joto** [comment] 2022-05-19 18:00
I am not sure whether we are doing ANALYZE. If not, this might actually be a problem. You can find out the answer to both of these questions by checking the output of `--log-sql` (or turning on logging in Postgres) as I mentioned above.

**Comment by mboeringa** [comment] 2022-05-19 18:49
I will try the logging option in osm2pgsql on a Liechtenstein extract.

For what it is worth: deleting 87M records from a 462M record data set of OpenStreetMap buildings takes just 30 minutes in both PG13 and PG14 using some Python scripting I created and a:

`DELETE FROM <TABLE_A> a USING <TABLE_B> b WHERE a.objectid = b.objectid`

type of SQL statement. The fact that the timings are the same, at least shows there is no wholesale regression issue in processing DELETE for PG14 versus 13.

**Comment by mboeringa** [comment] 2022-05-19 19:29
@joto 

I think one problem is clear, indeed no ANALYZE before the DELETE statements start being emitted by osm2pgsql. Interesting question remains why this is far less of an issue in PG13 than 14. Obviously, and likely, there may have been changes in the PostgreSQL planner that cause the difference:

```
2022-05-19 21:13:24  Creating id index on table 'planet_osm_line'...
2022-05-19 21:13:24  SQL: CREATE INDEX ON "osm"."planet_osm_line" USING BTREE (osm_id)  TABLESPACE "osm_k"
2022-05-19 21:13:24  Creating id index on table 'planet_osm_polygon'...
2022-05-19 21:13:24  SQL: CREATE INDEX ON "osm"."planet_osm_polygon" USING BTREE (osm_id)  TABLESPACE "osm_i"
2022-05-19 21:13:24  Creating id index on table 'planet_osm_transport_line'...
2022-05-19 21:13:24  SQL: CREATE INDEX ON "osm"."planet_osm_transport_line" USING BTREE (osm_id)  TABLESPACE "osm_j"
2022-05-19 21:13:24  Creating id index on table 'planet_osm_transport_polygon'...
2022-05-19 21:13:24  SQL: CREATE INDEX ON "osm"."planet_osm_transport_polygon" USING BTREE (osm_id)  TABLESPACE "osm_j"
2022-05-19 21:13:24  Creating id index on table 'planet_osm_admin'...
2022-05-19 21:13:24  SQL: CREATE INDEX ON "osm"."planet_osm_admin" USING BTREE (osm_id)  TABLESPACE "osm_k"
2022-05-19 21:13:24  Creating id indexes took 0s
2022-05-19 21:13:24  There are 1808 ways to reprocess...
2022-05-19 21:13:24  SQL: EXECUTE get_way(5363222)
etc...
2022-05-19 21:13:24  SQL: EXECUTE get_way(966204123)
2022-05-19 21:13:24  Dropping table 'planet_osm_nodes'
2022-05-19 21:13:24  SQL: DROP TABLE IF EXISTS "planet_osm_nodes"
2022-05-19 21:13:24  Table 'planet_osm_nodes' dropped in 0s
2022-05-19 21:13:24  Dropping table 'planet_osm_ways'
2022-05-19 21:13:24  SQL: DROP TABLE IF EXISTS "planet_osm_ways"
2022-05-19 21:13:25  Table 'planet_osm_ways' dropped in 1s
2022-05-19 21:13:25  Dropping table 'planet_osm_rels'
2022-05-19 21:13:25  SQL: DROP TABLE IF EXISTS "planet_osm_rels"
2022-05-19 21:13:25  Table 'planet_osm_rels' dropped in 0s
2022-05-19 21:13:25  Done postprocessing on table 'planet_osm_nodes' in 0s
2022-05-19 21:13:25  Done postprocessing on table 'planet_osm_ways' in 0s
2022-05-19 21:13:25  Done postprocessing on table 'planet_osm_rels' in 0s
2022-05-19 21:13:25  Clustering table 'planet_osm_point' by geometry...
2022-05-19 21:13:25  SQL: SET client_min_messages = WARNING
2022-05-19 21:13:25  SQL: DELETE FROM "osm"."planet_osm_polygon" WHERE osm_id IN (30969680,75393724,75393727,75393730,75393732,75393733,75393736,75393737,75393739,753
etc...
```
