### ISSUE TITLE
Can I skip parsing after crash?

### ISSUE THREAD

**Issue by molofeev** [openstreetmap/osm2pgsql#817] opened 2018-02-05 10:37 UTC
Output of osm2pgsql: 
<pre>
Node stats: total(4235496629), max(5290747187) in 33793s
Way stats: total(458618737), max(547543126) in 1300890s
Relation stats: total(5442482), max(7820612) in 741417s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Killed
</pre>

Can I modify osm2pgsql.cpp file by comment lines from 78 to 94, for restore progress of importing data?
Which options I need for run osm2pgsql again?

**Comment by lonvia** [comment] 2018-02-25 19:15
Index only is currently not possible. Duplicate of #799.

**Closed by lonvia** 2018-02-25 19:15 UTC
