### ISSUE TITLE
Ghost way in rendering

### ISSUE THREAD

**Issue by gvghia** [openstreetmap/osm2pgsql#1395] opened 2021-01-14 11:12 UTC
Hi, someone pointed met to this list for indicating following problem as in these examples: https://www.openstreetmap.org/#map=19/45.11380/-85.60905&layers=D and https://www.openstreetmap.org/way/254310728/history .  You see a strait ghost line crossing the boundary surface and which is not aligned in blue as data or can we selected, by 'what is here'
It seems there is a dependency for making boundary (or even polygon) relations, when they consist of 2 ways. When there are 3 or more ways, the direction of the ways does not matter. When there are only 2 and they have the same starting and end point, then to assemble the points for making the drawing, one way get inserted between the first and second point of the other way. This results in a ghost line from this second point to the endpoint. Solution is to eliminate this wrong behaviour in the renderer.  
Workaround is to reverse one of the two ways, so their points will be consecutive as a ring. Probably splitting one way in 2, could also do the trick.  This boundary is solved: https://www.openstreetmap.org/note/1948614#map=17/50.79530/4.60589&layers=N https://www.openstreetmap.org/note/1948614#map=17/50.79530/4.60589&layers=N The main and humanitarian layer exhibits this problem. Öpvn seems to have a better algorithm and is not having ghost ways. Background info is also in Help https://help.openstreetmap.org/questions/78014/deleting-a-ghost-way

**Comment by joto** [comment] 2021-01-14 13:15
Duplicate of #1394

**Closed by joto** 2021-01-14 13:15 UTC
