### ISSUE TITLE
Option to disable live parsing stats

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/osm2pgsql#1088] opened 2020-03-10 19:16 UTC
When importing an OSM file in background, osm2pgsql still prints its `"Processing: Node(122754k 189.4k/s) Way(11744k 18.58k/s) Relation(0 0.00/s)"` once for each 10k nodes or 1k ways (see `parse-osmium.hpp`). The issue with this is, when you redirect the output, it accumulates tens of thousands lines of this output. Which is completely unusable, and hogs the terminal when on error, it is suddently printed.

Could you please add an option, or check that osm2pgsql is printing its data not to a tty, to disable parsing stats updates? All other info should stay, of course.

**Comment by lonvia** [comment] 2020-03-10 19:26
Duplicate of #591.

**Closed by lonvia** 2020-03-10 19:26 UTC
