### ISSUE TITLE
WARNING:  there is no transaction in progress

### ISSUE THREAD

**Issue by OnkelTem** [openstreetmap/osm2pgsql#796] opened 2017-10-30 12:14 UTC
Hi there

I'm getting a list of warnings from PostgreSQL during the import process. They don't break the import procedure, but it could be a sign of that something goes wrong. My `osm2pgsql` command is:

```
$ osm2pgsql --create --slim --cache 2000 <database-info> file.pbf
```
and output has lots of the warnings like that:
```
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
...
```

**Comment by pnorman** [comment] 2017-10-30 19:39
This is expected.

I'm leaving it open because we don't have any open issues about if we can stop these `COMMIT;`s

**Comment by timautin** [comment] 2019-07-14 13:40
FWIW, I have the same behavior.

**Comment by lonvia** [comment] 2020-06-28 19:07
This can only happen in updates nowadays and even then it should be rare. The problem is that we create lots of threads for stage 1b and then only one or two items to process come in. We should still fix that at some point.

**Comment by joto** [comment] 2023-01-26 09:09
Since e64d8fde we are not doing any explicit commits any more, so I believe this has been fixed long ago. Closing here. Please open a new issue if this happens again.

**Closed by joto** 2023-01-26 09:09 UTC
