### ISSUE TITLE
Multipolygons: Output at openstreetmap.org depends on order and direction of MP members

### ISSUE THREAD

**Issue by hubgitti** [openstreetmap/osm2pgsql#518] opened 2015-12-15 19:15 UTC
After opening an issue at the mapnik github page, I was asked to bring it up here:

The heath multipolygon in the center of the map (link below) is only displayed correctly, if the outer forest multipolygon and all inner parts are sorted well and the ways are having the same direction:
http://www.openstreetmap.org/#map=16/47.3674/15.1881

This is not the behaviour as expected, the sequence or the direction of the ways should not matter:
http://wiki.openstreetmap.org/wiki/Relation:multipolygon

**Comment by pnorman** [comment] 2016-07-21 10:58
Can you supply a testcase XML file?

**Comment by pnorman** [comment] 2017-01-30 01:23
I tested reordering the relation members and was still getting same results. Without a testcase, or more details of what to change, I can't proceed any further.

**Comment by pnorman** [comment] 2017-03-03 02:57
Could not reproduce, closing as abandoned.

**Closed by pnorman** 2017-03-03 02:57 UTC
Labels: multipolygon, Needs more information
