### ISSUE TITLE
Tile Expiry Performance

### ISSUE THREAD

**Issue by intergalacticdata** [openstreetmap/osm2pgsql#946] opened 2019-08-14 19:07 UTC
This issue was posted to the osm-dev mailing list, per Nakaner's request, on May 29 2019. I am documenting it here as well so that it doesn't become lost.

While implementing a tile expiration solution I have run into some issues with the new tile expiry expansion. I'm afraid I do not have precise timings, but I'm seeing what appears to be at least an order of magnitude performance penalty, probably due to memory exhaustion.

Test machine is Debian stretch 4CPUs, 26GB RAM, SSD Array. Initial osm import was performed with osm2pgsql 0.92 and finished in under 48 hours.

Under 0.92 I was running multiple render chains while importing changesets. Tests w/ 0.96 have been run against an otherwise idle machine.

Database & flatnodes file were restored to initial state between each round of testing.

**WEEKLY** changeset using 0.92:
```
time $OSM2PGSQL --append -s -C 3000 -G --hstore -d gis -H $PGHOST -U \
$PGUSER -r xml changes.osc \
--flat-nodes /database/postgresql/OSM-FLATNODES --slim \
--number-processes 4 --style openstreetmap-carto.style \
--tag-transform-script openstreetmap-carto.lua -e19 -o \
$WORKDIR_OSM/expired-tiles
```
With -e19, I was able to import a WEEKLY changeset in roughly 24 hours.

Using git repository (5/27? pull):
```
time $OSM2PGSQL --append -s -C 3000 -G --hstore -d gis -H $PGHOST -U
$PGUSER -r xml changes.osc \
--flat-nodes /database/postgresql/OSM-FLATNODES --slim \
--number-processes 4 --style openstreetmap-carto.style \
--tag-transform-script openstreetmap-carto.lua -e10-16 -o \
$WORKDIR_OSM/expired-tiles
```
Consistently crashed w/ a bad alloc(). I didn't note any unusual output in the compile. **Crashes even with a 24 hour changeset.**

**DAILY** changeset using Debian backport to stretch (0.96):
-=-=-=-
As above, using -e10-16. 

22 hours spent processing a 24 hour changeset and still importing new relations. It's **35GB into swap, with osm2pgsql claiming 89% of the memory usage.**

I realize there is a large difference between zoom level 19 and 10-16, but I assume it should take significantly less RAM/CPU for 10-16.

**Same test as above WITHOUT expiring tiles:**
After 3 hours, the update has reached the same state of progress. osm2pgsql (debian backport) 0.96 maintains < 1GB of memory usage without expiring tiles. 

While expiring tiles, it ballooned to >50GB before being killed.

**WORK AROUND / FINAL THOUGHTS**
This is pretty clearly a memory leak. The initial test results reported by Nakaner for this patch show the same high levels of RAM usage (28GB for Europe alone).

My workaround uses 0.92 output and an external program to emulate what the newer tile expiration code is supposed to do:
https://intergalacticdata.com/public_domain/expandExpire.c

I've spoken w/ Nakaner and get the impression that he considers this memory usage to be a) normal and b) not due to tile expiration.

I submit that using osm2pgsql 0.92 plus my (admittedly simplistic) program does the same job in **2%** of the RAM required by 0.96.

0.96 will also complete the job in **2%** of the RAM if not asked to expire tiles.

I am not using tile expiration at this time due to business reasons and am therefore unable to dedicate any more time to this issue. I am merely documenting here in hopes of saving the next 'me' a week of their lives.

**Comment by lonvia** [comment] 2019-08-14 21:09
I'm not surprised. The expired tiles are saved in a set with 8 bytes per tile. Each parallel process keeps its own tile list which are merged only in the end. So that's in your case 4 * 8 bytes in the worst case. Add overhead for the hash and there is quite a bit of memory required for high zoom levels and large changesets. There is some room for improvement wrt the data structures used. However, there is also some cut-off point where I would consider the use of expiry unrealistic. Applying a weekly diff and creating expiry list for z19 is one of them. I wouldn't expect the expiry to be optimised for that. A daily diff at z16 should be doable though.

@Nakaner I trust you look at some point into optimising the data structures a bit.

**Comment by intergalacticdata** [comment] 2019-08-14 21:19
> Applying a weekly diff and creating expiry list for z19 is one of them. I wouldn't expect the expiry to be optimised for that. A daily diff at z16 should be doable though.

The formatting was not the clearest (I apologize), but please note this test:

DAILY changeset using Debian backport to stretch (0.96):
-=-=-=-
As above, using -e10-16.

22 hours spent processing a 24 hour changeset and still importing new relations. It's 35GB into swap, with osm2pgsql claiming 89% of the memory usage.

I realize there is a large difference between zoom level 19 and 10-16, but I assume it should take significantly less RAM/CPU for 10-16.

**Comment by Nakaner** [comment] 2019-08-14 21:59
> @Nakaner I trust you look at some point into optimising the data structures a bit.

The tile expiry list is a `std::unordered_set<uint64_t>`. See the [comment in the header file](https://github.com/openstreetmap/osm2pgsql/blob/master/expire-tiles.hpp#L175) for an explanation. I don't have any other method to save memory in mind except reducing the accuracy of the tile expiry either

* by storing the tile IDs on a smaller zoom level than requested or
* by using `uint32_t`

The first leads to a smaller `unordered_set` because one tile on zoom *z* consists of four tiles on zoom level *z+1*. But a smaller memory footprint can be achieved by just requesting tile expiry on a lower zoom level only and converting the tile IDs to higher zoom levels using a simple script processing the tile expiry list. The second option limits the largest zoom level to 16. However, tile.openstreetmap.org does tile expiry on zoom level 19 (they don't use the tile expiry by Osm2pgsql). I am against limiting tile expiry because I have the impression that it is not the problem.

I have done a few tests for the last few weeks. These are my results. I was working with Osm2pgsql commit 90e17f0e8c793487ca39cbf95501cd9c5daa33e2 (9 June 2019).

The import:

```
node cache: stored: 5249458158(100.00%), storage efficiency: 83.16% (dense blocks: 723375, sparse nodes: 193165767), hit rate: 100.00%
        Command being timed: "/home/michael/osm2pgsql/build/osm2pgsql -s -d expirytest --cache 60000 --hstore --flat-nodes /nvme/michael/osm2pgsqltest/flatnodes-import.flat --number-processes 4 --style /home/michael/git/openstreetmap-carto/openstreetmap-carto.style --tag-transform-script /home/michael/git/openstreetmap-carto/openstreetmap-carto.lua planet-latest.osm.pbf"
        Elapsed (wall clock) time (h:mm:ss or m:ss): 14:10:01
        Maximum resident set size (kbytes): 64444052
```

The application of diffs (I reimported with the command provided above) after the application of each diff:

```
Diff of one day, deduplicated, compressed with Gzip:
Osm2pgsql took 1837s overall
node cache: stored: 3592308(100.00%), storage efficiency: 78.40% (dense blocks: 370, sparse nodes: 775373), hit rate: 3.33%
        Command being timed: "/home/michael/osm2pgsql/build/osm2pgsql --append -s -d expirytest --cache 3000 --hstore joined-diff/joined-diff.osc.gz --flat-nodes /nvme/michael/osm2pgsqltest/flatnodes-import.flat --slim --number-processes 4 --style /home/michael/git/openstreetmap-carto/openstreetmap-carto.style --tag-transform-script /home/michael/git/openstreetmap-carto/openstreetmap-carto.lua -e10-16 -o joined-diff/expiries-gzip.txt"
        Elapsed (wall clock) time (h:mm:ss or m:ss): 30:41.98
        Maximum resident set size (kbytes): 50633788

the same, zoom levels 10-12 only:
about 695000 lines in the tile expiry file
        Command being timed: "/home/michael/osm2pgsql/build/osm2pgsql --append -s -d expirytest --cache 3000 --hstore joined-diff/joined-diff.osc.gz --flat-nodes /nvme/michael/osm2pgsqltest/flatnodes-import.flat --slim --number-processes 4 --style /home/michael/git/openstreetmap-carto/openstreetmap-carto.style --tag-transform-script /home/michael/git/openstreetmap-carto/openstreetmap-carto.lua -e10-12 -o joined-diff/expiries-gzip-10-12.txt"
        Elapsed (wall clock) time (h:mm:ss or m:ss): 29:07.44
        Maximum resident set size (kbytes): 49466208
```

Reducing the maximum zoom level of the tile expiry reduces the number of affected tiles because the set stores the tile in the largest zoom level only (lower zoom levels can be retrieved by bit shifts to the right). However, the influence on the total memory consumption is limited.

The lowest zoom level has no influence on the memory consumption because the tile IDs on all zoom levels below the largest requested zoom level are [created on the fly](https://github.com/openstreetmap/osm2pgsql/blob/master/expire-tiles.hpp#L95) during writing the output file.

```
Diff of one day, deduplicated, compressed with Gzip, zoom levels 15 and 16 only:
node cache: stored: 3592308(100.00%), storage efficiency: 78.40% (dense blocks: 370, sparse nodes: 775373), hit rate: 3.32%
        Command being timed: "/home/michael/osm2pgsql/build/osm2pgsql --append -s -d expirytest --cache 3000 --hstore joined-diff/joined-diff.osc.gz --flat-nodes /nvme/michael/osm2pgsqltest/flatnodes-import.flat --slim --number-processes 4 --style /home/michael/git/openstreetmap-carto/openstreetmap-carto.style --tag-transform-script /home/michael/git/openstreetmap-carto/openstreetmap-carto.lua -e15-16 -o joined-diff/expiries-gzip-15-16.txt"
        Elapsed (wall clock) time (h:mm:ss or m:ss): 33:40.85
        Maximum resident set size (kbytes): 50682908
```

This proves my statement the the largest requested zoom level decides how much memory the tile expiry list needs.

**Comment by pnorman** [comment] 2019-08-14 22:35
> The application of diffs (I reimported with the command provided above) after the application of each diff:

You've provided memory numbers for three runs with -e. How does this compare to the memory usage without generating an expired tile list?

**Comment by Nakaner** [comment] 2019-08-14 22:43
@pnorman 

Single day diff, deduplicated with Osmium, no expiry:

```
node cache: stored: 2640740(100.00%), storage efficiency: 78.01% (dense blocks: 271, sparse nodes: 582526), hit rate: 2.97%
        Command being timed: "/home/michael/osm2pgsql/build/osm2pgsql --append -s -d expirytest --cache 3000 --hstore single-day-diff/463-deduplicated.osc.gz --flat-nodes /nvme/michael/osm2pgsqltest/flatnodes-import.flat --slim --number-processes 4 --style /home/michael/git/openstreetmap-carto/openstreetmap-carto.style --tag-transform-script /home/michael/git/openstreetmap-carto/openstreetmap-carto.lua"
        Elapsed (wall clock) time (h:mm:ss or m:ss): 15:55.81
        Maximum resident set size (kbytes): 48364060
```

**Comment by lonvia** [comment] 2019-08-15 07:26
> However, the influence on the total memory consumption is limited.

I'm not convinced you can prove that by looking at the  "Maximum resident set size". The "Maximum resident set size" is dominated by the memory-mapped flatnode file. It is not a really helpful measurement here because how much of it is resident is mostly determined by your available RAM size. 

However, @intergalacticdata's statement "While expiring tiles, [the memory usage] ballooned to >50GB before being killed." is similarly unhelpful. Newer versions of osm2pgsql always balloon like this because of the memory-mapped flatnode file. It is not an indicator of a memory leak, nor reason for being OOM-killed.

**Comment by intergalacticdata** [comment] 2019-08-19 17:47
> However, @intergalacticdata's statement "While expiring tiles, [the memory usage] ballooned to >50GB before being killed." is similarly unhelpful. Newer versions of osm2pgsql always balloon like this because of the memory-mapped flatnode file. It is not an indicator of a memory leak, nor reason for being OOM-killed.

In that instance, the process was manually interrupted rather than OOM killed.

I wonder if this is two different issues. My earliest tests against CVS builds (late May) failed with bad alloc() while later tests against 0.96 stayed in the range of 1GB resident memory if not expiring tiles. I did not test the CVS build without tile expiration.

Nakaner's recent tests are against a June build and take ~50GB whether tiles are expired or not.

@Nakaner, is there any chance you run one more test with a 0.96 release build and no tile expiration?

Unfortunately, I no longer have the capability to run these tests. The 50x increase in required RAM really seems broken though.

**Comment by lonvia** [comment] 2020-01-03 21:18
I suspect the OOM kills that @intergalacticdata saw did come from libosmium using too much memory when building areas than from the tile expiry. So closing this issue. If you find a reproducable case of memory issues with expiry on the current osm2pgsql release, please open a new issue.

**Closed by lonvia** 2020-01-03 21:18 UTC
