### ISSUE TITLE
Import failing whilst processing relations

### ISSUE THREAD

**Issue by WCGL** [openstreetmap/osm2pgsql#329] opened 2015-04-10 10:10 UTC
Hi,

I've now had two attempts at importing a planet-latest.osm.pbf and both have failed at exactly the same point, the last output from osm2pgsql was;

> Processing: Node(2715748k 150.5k/s) Way(272021k 0.49k/s) Relation(613030 6.25/s)

the only clue I have to the problem is the content of the Postgres database log which has the following;

> 2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made >because the target machine actively refused it.
> 
> 2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_polygon, line 2
> 2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_polygon (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
> 2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
> 
> 2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_line, line 3
> 2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_line (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
> 2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
> 
> 2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_point, line 69718201
> 2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_point (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","capital","construction","covered","culvert","cutting","denomination","disused","ele","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","poi","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tunnel","water","waterway","wetland","width","wood","z_order",tags,way) FROM STDIN
> 2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

this goes on a bit but eventually ends with;

> 2015-04-10 08:27:32 BST FATAL:  terminating connection because protocol sync was lost

I have osm2pgsql and my Postgres database server running on the same PC, so I don't really understand how a communication failure can be the cause.

I launched the script with the following command;

> osm2pgsql -s -C 1500 --number-processes 6 -H localhost -G -k -c OpenStreetMap/planet-latest.osm.pbf -S /Styles/openstreetmap-carto.style -U postgres

Does anyone have a clue as to what is going on here?

**Comment by pnorman** [comment] 2015-04-10 16:01
1. Does this happen with smaller files and the same osm2pgsql options?

2. What does the PostgreSQL log say?

3. Why are you connecting over TCP/IP instead of local sockets?

**Comment by WCGL** [comment] 2015-04-10 16:26
Sorry, I'm pretty new to this process and Postgres.

1. I have not tried a smaller file, although I did manage to import this one on another system but using osmosis.  However that machine was far below spec and I have since abandoned it.

2. I've pasted the whole Postgres log below;

3. I wasn't aware there was a different connection method, is that likely to be cause of my problem?

>2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_polygon, line 2
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_polygon (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_line, line 3
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_line (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_point, line 69718201
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_point (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","capital","construction","covered","culvert","cutting","denomination","disused","ele","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","poi","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tunnel","water","waterway","wetland","width","wood","z_order",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST LOG:  incomplete message from client
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_polygon, line 2
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_polygon (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  unexpected EOF on client connection with an open transaction
>2015-04-10 08:27:28 BST LOG:  incomplete message from client
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_line, line 3
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_line (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST LOG:  incomplete message from client
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_point, line 69718201
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_point (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","capital","construction","covered","culvert","cutting","denomination","disused","ele","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","poi","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tunnel","water","waterway","wetland","width","wood","z_order",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  unexpected EOF on client connection with an open transaction
>2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST LOG:  unexpected EOF on client connection with an open transaction
>2015-04-10 08:27:28 BST LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_rels, line 612689
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_rels FROM STDIN;
	
>2015-04-10 08:27:28 BST LOG:  incomplete message from client
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_rels, line 612689
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_rels FROM STDIN;
	
>2015-04-10 08:27:28 BST ERROR:  unexpected EOF on client connection with an open transaction
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_rels, line 612689
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_rels FROM STDIN;
	
>2015-04-10 08:27:28 BST ERROR:  unexpected EOF on client connection with an open transaction
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_line, line 3
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_line (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  could not send data to client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_rels FROM STDIN;
	
>2015-04-10 08:27:28 BST LOG:  could not send data to client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_line (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST ERROR:  unexpected EOF on client connection with an open transaction
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_point, line 69718201
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_point (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","capital","construction","covered","culvert","cutting","denomination","disused","ele","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","poi","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tunnel","water","waterway","wetland","width","wood","z_order",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  could not send data to client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_point (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","capital","construction","covered","culvert","cutting","denomination","disused","ele","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","poi","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tunnel","water","waterway","wetland","width","wood","z_order",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST ERROR:  unexpected EOF on client connection with an open transaction
>2015-04-10 08:27:28 BST CONTEXT:  COPY planet_osm_polygon, line 2
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_polygon (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:28 BST LOG:  could not send data to client: No connection could be made because the target machine actively refused it.

	
>2015-04-10 08:27:28 BST STATEMENT:  COPY planet_osm_polygon (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
>2015-04-10 08:27:29 BST FATAL:  terminating connection because protocol sync was lost
>2015-04-10 08:27:29 BST FATAL:  terminating connection because protocol sync was lost
>2015-04-10 08:27:29 BST FATAL:  terminating connection because protocol sync was lost
>2015-04-10 08:27:32 BST FATAL:  terminating connection because protocol sync was lost

**Comment by pnorman** [comment] 2015-04-10 16:52
oops. I thought you had pasted a different file, not the log before.

Try with the `tests/liechtenstein-2013-08-03.osm.pbf` file. If that works, try a ~10 MB pbf.

What version of osm2pgsql do you have?

You should set up a postgresql user with the same name as your system username, and then be able to use osm2pgsql without the -h or -U options.

What's happening is osm2pgsql has stopped responding to postgres.

**Comment by WCGL** [comment] 2015-04-10 21:25
Thanks, I will give this a go.

I'm using osm2pgsql SVN version 0.83.0 (64bit id space)

**Comment by pnorman** [comment] 2015-04-10 21:27
Try a more recent version. 0.86.0 for the C version, or 0.87.x for C++.

**Comment by pnorman** [comment] 2015-07-02 06:54
User never verified on a recent version, and the issue doesn't show up on most setups.

**Comment by simonpoole** [comment] 2015-09-22 21:16
We just had a reoccurance of the issue reported  in a setup with postgres and osm2pgsql in seperate Docker containers. I suspect that this is due to the idle connections for the way and relation tables timing out (reason not clear but may be a postgresql artifact) while the nodes are being processed.

**Comment by hyperknot** [comment] 2015-09-28 04:33
I had the exact thing happen to me. 

log:
```
[1001]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[1003]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[999]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[998]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[999]: [4-2] CONTEXT:  COPY planet_osm_line, line 36811394
[1003]: [4-2] CONTEXT:  COPY planet_osm_ways, line 82155938
[998]: [4-2] CONTEXT:  COPY planet_osm_point, line 76244780
[1003]: [4-3] STATEMENT:  COPY planet_osm_ways FROM STDIN;
[999]: [4-3] STATEMENT:  COPY planet_osm_line (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
[1003]: [4-4] 	
[998]: [4-3] STATEMENT:  COPY planet_osm_point (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","capital","construction","covered","culvert","cutting","denomination","disused","ele","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","poi","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tunnel","water","waterway","wetland","width","wood","z_order",tags,way) FROM STDIN
[1001]: [4-2] CONTEXT:  COPY planet_osm_roads, line 3524268
[1001]: [4-3] STATEMENT:  COPY planet_osm_roads (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
[1000]: [3-1] ERROR:  unexpected EOF on client connection with an open transaction
[1002]: [3-1] ERROR:  unexpected EOF on client connection with an open transaction
[1004]: [3-1] ERROR:  unexpected EOF on client connection with an open transaction
[1000]: [3-2] CONTEXT:  COPY planet_osm_polygon, line 1
[1002]: [3-2] CONTEXT:  COPY planet_osm_nodes, line 1
[1004]: [3-2] CONTEXT:  COPY planet_osm_rels, line 1
[1002]: [3-3] STATEMENT:  COPY planet_osm_nodes FROM STDIN;
[1004]: [3-3] STATEMENT:  COPY planet_osm_rels FROM STDIN;
[1000]: [3-3] STATEMENT:  COPY planet_osm_polygon (osm_id,"access","addr:housename","addr:housenumber","addr:interpolation","admin_level","aerialway","aeroway","amenity","area","barrier","bicycle","brand","bridge","boundary","building","construction","covered","culvert","cutting","denomination","disused","embankment","foot","generator:source","harbour","highway","historic","horse","intermittent","junction","landuse","layer","leisure","lock","man_made","military","motorcar","name","natural","office","oneway","operator","place","population","power","power_source","public_transport","railway","ref","religion","route","service","shop","sport","surface","toll","tourism","tower:type","tracktype","tunnel","water","waterway","wetland","width","wood","z_order","way_area",tags,way) FROM STDIN
[1002]: [3-4] 	
[1004]: [3-4] 	
[1002]: [5-1] FATAL:  terminating connection because protocol sync was lost
[1004]: [5-1] FATAL:  terminating connection because protocol sync was lost
[1000]: [5-1] FATAL:  terminating connection because protocol sync was lost
[999]: [6-1] FATAL:  terminating connection because protocol sync was lost
[1001]: [6-1] FATAL:  terminating connection because protocol sync was lost
[998]: [6-1] FATAL:  terminating connection because protocol sync was lost
[1003]: [6-1] FATAL:  terminating connection because protocol sync was lost
```

config
```
# default parts

datestyle = 'iso, mdy'
default_text_search_config = 'pg_catalog.english'
lc_messages = 'C'
lc_monetary = 'C'
lc_numeric = 'C'
lc_time = 'C'
log_destination = 'syslog'
log_timezone = 'UTC'
max_connections = 100
timezone = 'UTC'
update_process_title = off


# changed parts

autovacuum = off
fsync = off
synchronous_commit = off
full_page_writes = off

shared_buffers = 512MB
work_mem = 64MB
maintenance_work_mem = 1024MB
wal_buffers = 16MB

checkpoint_segments = 64
checkpoint_completion_target = 0.9
random_page_cost = 2.0
cpu_tuple_cost = 0.05

effective_io_concurrency = 2
```

command
```
osm2pgsql --create --slim --drop --flat-nodes flat.bin --cache 14000 --number-processes 6 --hstore --database $DB_NAME $PBF_FILE
```

config: FreeBSD 10.2, PostgreSQL 9.3.9, PostGIS 2.1.7, osm2pgsql 0.87.2, default ZFS

Note: I disabled swap on purpose as I prefer a failed import over one which slows down because of swapping. On the other hand, still in the processing node-way-relation part I've not seen over 7 GB of memory usage with the above settings.

**Comment by pnorman** [comment] 2015-09-28 04:57
> command
```
osm2pgsql --create --slim --drop --flat-nodes flat.bin --cache 14000 --number-processes 6 --hstore --database $DB_NAME $PBF_FILE
```
> 
> config: FreeBSD 10.2, PostgreSQL 9.3.9, PostGIS 2.1.7, osm2pgsql 0.87.2, default ZFS

Just to confirm, you didn't set `$PGHOST` or anything? A theory had been that the cause was TCP/IP timeout related, but this is using local sockets, so that seems to rule it out.

As a virtually identical import line works fine on my FreeBSD box, it's hard to help. 

Is this repeatable?

How long had osm2pgsql been running when it errored?

What was the osm2pgsql output when it errored?

How many hardware threads does your system have, or what CPU?

How much RAM?

-----

Re-ordering the log by PID, I get this

```
[998]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[998]: [4-3] STATEMENT:  COPY planet_osm_point (<columnlist>) FROM STDIN
[998]: [4-2] CONTEXT:  COPY planet_osm_point, line 76244780
[998]: [6-1] FATAL:  terminating connection because protocol sync was lost

[999]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[999]: [4-2] CONTEXT:  COPY planet_osm_line, line 36811394
[999]: [4-3] STATEMENT:  COPY planet_osm_line (<columnlist>) FROM STDIN
[999]: [6-1] FATAL:  terminating connection because protocol sync was lost

[1000]: [3-1] ERROR:  unexpected EOF on client connection with an open transaction
[1000]: [3-2] CONTEXT:  COPY planet_osm_polygon, line 1
[1000]: [3-3] STATEMENT:  COPY planet_osm_polygon (<columnlist>) FROM STDIN
[1000]: [5-1] FATAL:  terminating connection because protocol sync was lost

[1001]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[1001]: [4-2] CONTEXT:  COPY planet_osm_roads, line 3524268
[1001]: [4-3] STATEMENT:  COPY planet_osm_roads (<columnlist>) FROM STDIN
[1001]: [6-1] FATAL:  terminating connection because protocol sync was lost

[1002]: [3-1] ERROR:  unexpected EOF on client connection with an open transaction
[1002]: [3-2] CONTEXT:  COPY planet_osm_nodes, line 1
[1002]: [3-3] STATEMENT:  COPY planet_osm_nodes FROM STDIN;
[1002]: [3-4]   
[1002]: [5-1] FATAL:  terminating connection because protocol sync was lost

[1003]: [4-1] ERROR:  unexpected EOF on client connection with an open transaction
[1003]: [4-2] CONTEXT:  COPY planet_osm_ways, line 82155938
[1003]: [4-3] STATEMENT:  COPY planet_osm_ways FROM STDIN;
[1003]: [4-4]   
[1003]: [6-1] FATAL:  terminating connection because protocol sync was lost

[1004]: [3-1] ERROR:  unexpected EOF on client connection with an open transaction
[1004]: [3-2] CONTEXT:  COPY planet_osm_rels, line 1
[1004]: [3-3] STATEMENT:  COPY planet_osm_rels FROM STDIN;
[1004]: [3-4]   
[1004]: [5-1] FATAL:  terminating connection because protocol sync was lost
```

Still nothing that helps me identify the problem.

**Comment by hyperknot** [comment] 2015-09-28 05:02
I'm trying to repeat it, this time with the exact config from http://paulnorman.ca/blog/2014/11/new-server-postgresql-tuning/

What is repeatable though is that node processing happens very quickly (1400 k/s) but ways slow down a _lot_, to like 6 / sec. I've tried 3 times but I never had the processing part complete within 24 hours.

Server is E3 1270 v3, 32 GB RAM, 2 x 1 TB HDD, ZFS mirror

**Comment by hyperknot** [comment] 2015-09-28 05:21
This might be totally harmless and only happening once the user Ctrl + C-s the running osm2pgsql process. I could reproduce it by Ctrl + C-ing the processing part and my previous one might have been linked to an earlier aborting.

**Comment by lonvia** [comment] 2015-09-28 07:19
For the record: the TCP error we were discussing on IRC is actually #159 where the connection is found closed when the first way is copied. This one looks different. It breaks in the middle of relations. Ctrl-C or OOM killing of osm2pgsql is a more likely cause here.

**Comment by lonvia** [comment] 2017-01-15 21:48
Closing again as most likely an OOM failure.

**Closed by lonvia** 2017-01-15 21:48 UTC
