### ISSUE TITLE
parameter -a fails

### ISSUE THREAD

**Issue by xhancar** [openstreetmap/osm2pgsql#366] opened 2015-07-02 09:40 UTC
I tried to add Kosovo to Serbia with this command:

osm2pgsql -d serbiaLL -l --number-processes 2  -a /var/tmp/kosovo-latest.osm.pbf --style openstreetmap-carto.style

but this error occurred:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  middle_ram_t::relations_using_way is unimlpemented, and should not have been called. This is probably a bug, please report it at https://github.com/openstreetmap/osm2pgsql/issues
```

This is all the log:
```
osm2pgsql SVN version 0.87.2-dev (64bit id space)          
                                                           
Using built-in tag processing pipeline                     
Using projection SRS 4326 (Latlong)                        
Setting up table: planet_osm_point                         
Setting up table: planet_osm_line                          
Setting up table: planet_osm_polygon                       
Setting up table: planet_osm_roads                         
Allocating memory for dense node cache                     
Allocating dense node cache in one big chunk               
Allocating memory for sparse node cache                    
Sharing dense sparse                                       
Node-cache: cache=800MB, maxblocks=102400*8192, allocation method=3
Mid: Ram, scale=10000000                                   
                                                           
Reading in file: /var/tmp/kosovo-latest.osm.pbf            
Processing: Node(934k 934.7k/s) Way(49k 16.62k/s) Relation(230 115.00/s)  parse time: 5s
Node stats: total(934664), max(3628872651) in 0s           
Way stats: total(49856), max(357432502) in 3s              
Relation stats: total(232), max(5324092) in 2s             
Committing transaction for planet_osm_point                
Committing transaction for planet_osm_line                 
Committing transaction for planet_osm_polygon              
Committing transaction for planet_osm_roads                
Using built-in tag processing pipeline                     
Using built-in tag processing pipeline                     
                                                           
Going over pending ways...                                 
        16877 ways are pending                             
                                                           
Using 2 helper-processes                                   
terminate called after throwing an instance of 'std::runtime_error'
  what():  middle_ram_t::relations_using_way is unimlpemented, and should not have been called. This is probably a bug, please report it at https://github.com/openstreetmap/osm2pgsql/issues
```

**Comment by pnorman** [comment] 2015-07-02 20:05
duplicate of #213

**Closed by pnorman** 2015-07-02 20:05 UTC
