### ISSUE TITLE
windows version, please

### ISSUE THREAD

**Issue by luzhskij** [openstreetmap/osm2pgsql#472] opened 2015-10-25 10:00 UTC
Hello! But could not someone put the latest version of windows?
The latter of which can be found online - 0.85-cpp-win-cmake (64bit id space).

**Comment by alex85k** [comment] 2015-10-25 10:26
Here is the development build of current 0.88 branch:
https://ci.appveyor.com/project/alex85k/osm2pgsql-cmake/build/artifacts
(about 2 weeks ago)

The current automatic builds will be here, when I'll fix them:
https://ci.appveyor.com/project/alex85k/osm2pgsql/build/artifacts

**Comment by alex85k** [comment] 2015-10-25 10:53
Automatic build is ready:
https://ci.appveyor.com/project/alex85k/osm2pgsql/build/artifacts

**Comment by luzhskij** [comment] 2015-10-25 11:25
Thank you so much!

**Comment by alex85k** [comment] 2015-10-25 11:30
Be careful, not one is sure if it works correct on big files :)

**Comment by luzhskij** [comment] 2015-10-25 11:37
But what use to import Planet PBF File to pgsql?

**Comment by alex85k** [comment] 2015-10-25 12:36
It may work. Huge restructuring was done after 0.85 and no one tried that on big data.

It is better to start with on one country extract and when it works correctly (render etc.), give it a planet file. Windows support n in development.

Please let us know if it will pass correctly or in case of any problems :)

**Comment by pnorman** [comment] 2015-10-25 23:19
I think this is a duplicate of #17. At this point, I'd recommend building Windows from the branch in #460 rather than master.

For large files, it is not generally recommended that you use Windows for running a large database. This doesn't mean you couldn't use osm2pgsql on Windows and connect it to a large database server, but no one I know does this, since you still need a machine running Linux, BSD, or OS X.

**Comment by achapkowski** [comment] 2015-10-26 10:53
@pnorman - can you explain your statement a bit more?  Are there recommended design docs out there for a windows system or windows/linux hybrid?

Thanks

**Comment by pnorman** [comment] 2015-10-26 23:38
> @pnorman - can you explain your statement a bit more? Are there recommended design docs out there for a windows system or windows/linux hybrid?

PostgreSQL 9.0 High Performance states "In practice, systems doing the sort of large queries that most benefit from this are not commonly practical on Windows anyway, due to its limitations in shared memory and connection capacity". You can find other statements about the limitations of Windows for large databases, and osm2pgsql whole planet imports are generally large. See also https://wiki.postgresql.org/wiki/Running_%26_Installing_PostgreSQL_On_Native_Windows

If you are not operating the database server yourself, it's then not an issue, and you might want to then run osm2pgsql on a different machine, which might end up being Windows. This is generally unlikely.

**Closed by pnorman** 2015-10-26 23:38 UTC
