### ISSUE TITLE
Potential memory leak when running without flatnode option

### ISSUE THREAD

**Issue by timautin** [openstreetmap/osm2pgsql#931] opened 2019-05-13 22:05 UTC
Hello,

When inserting the planet PBF file, the process starts normally, completely fills my RAM (64 GB), fills my swap (32 GB) and then the process is killed.

My server has 8 core / 16 threads, and I'm using this command:

`osm2pgsql -d osm --create --slim -G --hstore -C 30000 --number-processes 14 --tag-transform-script ~/src/map-styles/openstreetmap-carto/openstreetmap-carto.lua --style ~/src/map-styles/openstreetmap-carto/openstreetmap-carto.style ~/data/osm-pbf/planet-latest.osm.pbf`

This fills the RAM+swap in 1/2 h, and gets killed.

When using lower values for the memory, it takes more time to fill the RAM, but is still killed in the end. On another server I manager the import with -C 2000 and --number-processes 2. But it took a long time and I'd like to run it as fast as possible.

What parameters should I use?

**Comment by pnorman** [comment] 2019-05-13 22:55
What version are you running? Does it still happen with --flat-nodes?

**Comment by timautin** [comment] 2019-05-13 23:20
Sorry, latest version, it's a fresh install.
I'm retrying with --flat-nodes (and -C 30000 --number-processes 14). Can we delete the nodes.cache file after the import?

**Comment by lonvia** [comment] 2019-05-14 07:04
Latest version as in 'latest release' (aka 0.96) or as in github current master?

**Comment by timautin** [comment] 2019-05-14 07:19
```
osm2pgsql --version
osm2pgsql version 0.96.0 (64 bit id space)

Compiled using the following library versions:
Libosmium 2.15.1
Lua 5.2.4
```

I downloaded it using git clone git://github.com/openstreetmap/osm2pgsql.git, so I'd say 
it's branch master, and that master's version is 0.96.

Anyway it seems to be working with --flat-nodes, it's been running all the night and is now inserting ways, thanks a lot!

It seems to be using only one thread though, but I guess that only some parts of the process are multithreaded?

**Comment by lonvia** [comment] 2019-05-14 07:29
It's using only one thread to write to the database. The pbf is processed multithreaded.

Please leave the issue open. It sounds like there is a memory leak when not using flatnode files. I need to see if I can reproduce that here. I've adapted the issue title accordingly to find it later.

**Comment by woodpeck** [comment] 2019-05-14 07:34
Note that PostgreSQL can allocate its configured `work_mem` for every database connection. An osm2pgsql run with --number-processes 16 can cause memory usage of `shared_buffers` + `maintenance_work_mem` + 16 * `work_mem` on PostgreSQL's side alone, not even counting osm2pgsql's own memory footprint.

**Comment by lonvia** [comment] 2019-05-14 07:39
@timautin can you actually confirm _when_ your osm2pgsql got killed. What was the last line it printed?

**Comment by pnorman** [comment] 2019-05-14 16:02
> An osm2pgsql run with --number-processes 16 can cause memory usage of `shared_buffers` + `maintenance_work_mem` + 16 * `work_mem` on PostgreSQL's side alone

Not for large values of work_mem. The queries which take a lot of memory are limited to the indexing phase, which doesn't have 16 queries to run, and at half an hour in, we're looking at processing nodes or processing ways.

**Comment by timautin** [comment] 2019-05-14 17:24
> @timautin can you actually confirm _when_ your osm2pgsql got killed. What was the last line it printed?

The last line was something like:

`Processing: Node(175600k 3192.7k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Killed`

I'll be able to run a real test if you want once my import is done.

**Comment by lonvia** [comment] 2019-05-20 20:31
I've tried this now and can't reproduce the issue. Valgrind does not show any memory leaks. Neither does top report an undue growth of memory.

@timautin If you have the setup still around, could you try and import a small excerpt (for example [Liechtenstein](http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf) with the original osm2pgsql paramters under valgrind to see if it reports anything for you? (`apt install valgrind` and then `valgrind osm2pgsql <paramters>`)

**Comment by timautin** [comment] 2019-05-22 20:33
@lonvia Valgrind didn't find anything:

`Osm2pgsql took 231s overall
node cache: stored: 2398306(100.00%), storage efficiency: 51.26% (dense blocks: 59, sparse nodes: 2097741), hit rate: 100.00%
==7638== Warning: set address range perms: large range [0x59e43028, 0x7b0e43058) (noaccess)
==7638== 
==7638== HEAP SUMMARY:
==7638==     in use at exit: 0 bytes in 0 blocks
==7638==   total heap usage: 11,326,339 allocs, 11,326,339 frees, 35,209,940,432 bytes allocated
==7638== 
==7638== All heap blocks were freed -- no leaks are possible
==7638== 
==7638== For counts of detected and suppressed errors, rerun with: -v
==7638== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
`

I'm suspecting a hardware problem: when tring to import my contours shapefiles to PostGIS with ogr2ogr, after a few hours the server crashes and reboots. I just reinstalled everything from scratch and the problem is still there. It worked on another server, with the same version of GDAL. On the other hand, I asked Hetzner (my host) to run a hardware checkup and it didn't find anything. It doesn't mean that there's no problem though.

**Comment by lonvia** [comment] 2019-05-22 21:01
Did you modify the PostgreSQL server configuration? It might actually be the database that eats all memory.

**Comment by lonvia** [comment] 2019-05-22 21:01
Did you modify the PostgreSQL server configuration? It might actually be the database that eats all memory.

**Comment by timautin** [comment] 2019-05-25 17:09
@lonvia yes, here's what I added at the end of my postgresql.conf:

```
random_page_cost = 1.1
wal_buffers = 16MB
effective_cache_size = 48GB
maintenance_work_mem = 4GB
shared_buffers = 8MB
work_mem = 128MB
autovacuum = on
effective_io_concurrency = 200
max_connections = 300
checkpoint_completion_target = 0.7
default_statistics_target = 100
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 12
max_parallel_workers_per_gather = 6
max_parallel_workers = 12
```

Do you see something wrong?

I exchanged my server with another one. The GDAL problem is gone, so I indeed had a hardware problem. But I still get the same behavior for osm2pgsql.

**Comment by pnorman** [comment] 2019-05-26 23:16
What do the kernel logs about the OOM killer say? I'm trying to think of ways to isolate if it's an osm2pgsql issue, or a DB issue.

For testing purposes, can you try with `--number-processes 1`.

It shouldn't matter for this bug, but that shared_buffers is extremely low. More conventional would be 8-16GB.

**Comment by timautin** [comment] 2019-05-29 21:45
Hi @pnorman ,

I retried with:

```
synchronous_commit = off
fsync = off
random_page_cost = 1.1
wal_buffers = 16MB
effective_cache_size = 48GB
maintenance_work_mem = 8GB
shared_buffers = 16GB
work_mem = 1GB
autovacuum = on
effective_io_concurrency = 200
max_connections = 300
checkpoint_completion_target = 0.7
default_statistics_target = 100
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 16
max_parallel_workers_per_gather = 8
max_parallel_workers = 16
```

and

time osm2pgsql \
    -d osm \
    --create --slim -G --hstore \
    -C 20000 \
    --number-processes 1 \
    --tag-transform-script ~/src/map-styles/openstreetmap-carto/openstreetmap-carto.lua \
    --style ~/src/map-styles/openstreetmap-carto/openstreetmap-carto.style \
    planet-latest.osm.pbf \
    --flat-nodes /ssd/flat-nodes/osm.cache

And it worked, respecting the 20GB limit.

I found this in the kern.log:

```
May 25 13:41:46 EX62 kernel: [100019.247398] Out of memory: Kill process 18243 (osm2pgsql) score 992 or sacrifice child
May 25 13:41:46 EX62 kernel: [100019.247558] Killed process 18243 (osm2pgsql) total-vm:112168708kB, anon-rss:64966476kB, file-rss:0kB, shmem-rss:0kB
May 25 13:41:49 EX62 kernel: [100022.248592] oom_reaper: reaped process 18243 (osm2pgsql), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
Not sur if that helps??

**Comment by jbone80** [comment] 2019-07-18 14:16
I am new to this osm2pgsql, work required I learn it.  Bear with the first part, but it was part of the process I was using to have all the memory consumed.  I was running into this error:

`F:\osm2pgsql-bin>osm2pgsql C:\planet-190415.osm.pbf -v -c -d osm -U postgres -W --hstore
osm2pgsql version 0.96.0 (64 bit id space)

Password:
Allocating memory for sparse node cache
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=1
Using built-in tag processing pipeline
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads

Reading in file: C:\planet-190415.osm.pbf
Using PBF parser.
Processing: Node(41200k 5885.7k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Node cache size is too small to fit all nodes. Please increase cache size
Error occurred, cleaning up`

So I started running it with the -C flag set to 40000 and this is what I get when it is running:

![Memory_consuming](https://user-images.githubusercontent.com/40067691/61464160-0becb800-a933-11e9-8cad-8715796426dd.JPG)

Windows is telling me osm2pgsql is consuming all of the memory, but even with the -C flag set to 40000 I am still getting this:

`F:\osm2pgsql-bin>osm2pgsql C:\planet-190415.osm.pbf -v -c -d osm -U postgres -W -C 40000 --hstore
osm2pgsql version 0.96.0 (64 bit id space)

Password:
Allocating memory for sparse node cache
Node-cache: cache=40000MB, maxblocks=640000*65536, allocation method=1
Using built-in tag processing pipeline
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads

Reading in file: C:\planet-190415.osm.pbf
Using PBF parser.
Processing: Node(2619980k 5446.9k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Node cache size is too small to fit all nodes. Please increase cache size
Error occurred, cleaning up`

For some reason today it isn't dying, it killed my inject yesterday 3 times.  Yesterday it would kill the process before it finished loading all the nodes, before it transitions to loading the "Way" portion of it. 
 When I add the -F and -s flag it works just fine.   All I have to do is add the -F flag and it works, I haven't specified a node file for it to use at all.  However, I have it stored on a drive that is 400GB and it consumes every last bit of that during the injection and dies because it runs out of space.  I don't know how much space I should give it.

**Comment by lonvia** [comment] 2019-07-19 18:28
@jbone80 Please do not add questions to random tickets. Your issue is completely unrelated. 

That said: use slim mode. A planet does not fit into memory unless you have a very,very big machine.

**Comment by lonvia** [comment] 2019-07-19 18:31
Closing issue as the resolution seems to be that too many threads have been used.

**Closed by lonvia** 2019-07-19 18:31 UTC

**Comment by timautin** [comment] 2019-07-19 18:41
@lonvia well, the doc might need some clarification ;)
