### ISSUE TITLE
osm_timestamp is empty

### ISSUE THREAD

**Issue by tomass** [openstreetmap/osm2pgsql#560] opened 2016-03-21 20:40 UTC
Column osm_timestamp in imported/created tables (planet_osm_point, planet_osm_polygon etc.) is null:

<pre>=> select count(1) from planet_osm_point where osm_timestamp is not null;
 count 
-------
     0
(1 row)</pre>

I'm importing lithuania pbf file from geofabrik. I've converted pbf to xml and confirmed that timestamp IS filled in pbf file. XML excerpt:
&lt;node id="15389895" lat="54.7321714" lon="25.2436895" version="5" timestamp="2015-10-26T13:16:19Z" changeset="34881555" uid="1241595" user="xxx"/&gt;

osm2pgsql provided by fedora rpm package on 64bit fedora OS
<pre>$ osm2pgsql --version
osm2pgsql SVN version 0.88.1 (64bit id space)</pre>

Import is done with the following call:
<pre>osm2pgsql -d gis -S osm2pgsql.style --extra-attributes lithuania-latest.osm.pbf</pre>

osm2pgsql.style file has these lines (among many others)
<pre>...
node,way   osm_user     text
node,way   osm_timestamp timestamptz(0)
...</pre>

Note: osm_user field IS filled in
Note: this used to work, but stopped two-three weeks ago or so, process is automated so I didn't noticed it right away.

I'm out of ides what to try/check...

**Comment by pnorman** [comment] 2016-03-21 20:45
duplicate of #137, and fixed in 0.90.0

**Closed by pnorman** 2016-03-21 20:45 UTC
