### ISSUE TITLE
oms2pgsql failed on applying changesets to existing full planet database

### ISSUE THREAD

**Issue by thbeutin** [openstreetmap/osm2pgsql#910] opened 2019-02-13 15:00 UTC
Hi, i'm running a full planet OSM database and constantly apply updates. After some months (or years?) i get a mysteriuos error:
insert_rel failed: ERROR:  value "42698" is out of range for type smallint
(7)
Arguments were: 2632934, 4616, 42698, { <very long list of  ints> }, { long list of node_ids and labels }, { reasonable long tag list }

osm2pgsql bails out having exit code 1

btw: the changeset data is from:
$ osmconvert --out-statistics changes.osc.gz | grep '^timestamp m'
timestamp min: 2019-02-11T09:29:19Z
timestamp max: 2019-02-11T09:33:01Z

Is there any way to come around this update?

**Comment by thbeutin** [comment] 2019-02-13 16:12
Some more information i forgot to give at the first place:
osm2pgsql SVN version 0.82.0 (64bit id space)

Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
Setting up table: planet_osm_line
NOTICE:  table "planet_osm_line_tmp" does not exist, skipping
Setting up table: planet_osm_polygon
NOTICE:  table "planet_osm_polygon_tmp" does not exist, skipping
Setting up table: planet_osm_roads
NOTICE:  table "planet_osm_roads_tmp" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=8192MB, maxblocks=1048577*8192, allocation method=11
Mid: loading persistent node cache from /scratch/flat_nodes/flat_nodes
Maximum node in persistent node cache: 6271131647
Mid: pgsql, scale=100 cache=8192
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: changes.osc.gz
insert_rel failed: ERROR:  value "42698" is out of range for type smallint
(7)
Arguments were: 2632934, 4616, 42698, {...

If needed i can provide the full log and the change file as well.

**Comment by woodpeck** [comment] 2019-02-13 16:53
See https://lists.openstreetmap.org/pipermail/talk/2019-February/082064.html - a newer version of osm2pgsql should fix it.

**Comment by pnorman** [comment] 2019-02-13 22:13
Duplicate of #713 - as woodpeck says, a newer version  of osm2pgsql will fix it.

**Closed by pnorman** 2019-02-13 22:13 UTC

**Comment by thbeutin** [comment] 2019-02-15 15:50
> See https://lists.openstreetmap.org/pipermail/talk/2019-February/082064.html - a newer version of osm2pgsql should fix it.

Thanks for the quick reply! Do you know if v0.94.0(1) is new enough to deal with this issue?

(1) osm2pgsql v0.94.0 comes with ubuntu 18.04 LTS

**Comment by pnorman** [comment] 2019-02-16 06:32
> Thanks for the quick reply! Do you know if v0.94.0(1) is new enough to deal with this issue?

0.94.0 has the fix.
