### ISSUE TITLE
uncaught exception of type std::runtime_error: middle_ram_t::relations_using_way is unimlpemented

### ISSUE THREAD

**Issue by cmyk** [openstreetmap/osm2pgsql#307] opened 2015-03-03 16:50 UTC
Used this brew binary on yosemite:
https://homebrew.bintray.com/bottles/osm2pgsql-0.87.0.yosemite.bottle.tar.gz

`
wsPhil:~ cmyk$ osm2pgsql --append -d osm -P 5432 -S /Volumes/Work/Peakhunter-Map/default.style /Volumes/Work/Peakhunter-Map/liechtenstein-latest.osm.bz2
osm2pgsql SVN version 0.87.0 (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=102400*8192, allocation method=3
Mid: Ram, scale=100

Reading in file: /Volumes/Work/Peakhunter-Map/liechtenstein-latest.osm.bz2
Processing: Node(127k 127.8k/s) Way(13k 13.34k/s) Relation(337 168.50/s)  parse time: 4s
Node stats: total(127839), max(3377945578) in 1s
Way stats: total(13340), max(330794224) in 1s
Relation stats: total(337), max(4638609) in 2s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Using built-in tag processing pipeline

Going over pending ways...
	8606 ways are pending

Using 1 helper-processes
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: middle_ram_t::relations_using_way is unimlpemented, and should not have been called. This is probably a bug, please report it at https://github.com/openstreetmap/osm2pgsql/issues
Abort trap: 6
`

**Comment by pnorman** [comment] 2015-03-03 16:53
duplicate of #213

**Closed by pnorman** 2015-03-03 16:53 UTC

**Comment by cmyk** [comment] 2015-03-03 17:21
Sorry about that, but I did search for "middle_ram" and it didn't find a thing in the issues.
