### ISSUE TITLE
skip table sorting and (re)indexing after importing osm data

### ISSUE THREAD

**Issue by thbeutin** [openstreetmap/osm2pgsql#255] opened 2015-01-18 11:15 UTC
Since i have to do statistics on osm tags i would really appreciate to have an option to skip the table sorting and (re)indexing after importing the osm data into the database.

I have to reorder the data to suit my needs anyway (which includes to build custom indexes), so this would save many hours of import time to me.

Another suggestion instead of an option: what if there would be a default sql file containing the current commands which could be tweaked by experienced users to fit their needs?

**Comment by pnorman** [comment] 2015-01-18 12:25
duplicate of #27

**Closed by pnorman** 2015-01-18 12:25 UTC
