### ISSUE TITLE
Probably a bug

### ISSUE THREAD

**Issue by tanya94** [openstreetmap/osm2pgsql#320] opened 2015-03-27 07:13 UTC
I had such an error:

#osm2pgsql RU-ME.osm.pbf -a -d gis -U postgres -W -C 1000 --hstore --cache-strategy sparse
osm2pgsql SVN version 0.87.3-dev (64bit id space)

Password:
Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for sparse node cache
Node-cache: cache=1000MB, maxblocks=128000*8192, allocation method=1
Mid: Ram, scale=100

Reading in file: RU-ME.osm.pbf
Processing: Node(1797k 1797.5k/s) Way(144k 28.96k/s) Relation(7740 1105.71/s)  parse time: 13s
Node stats: total(1797513), max(3406178873) in 1s
Way stats: total(144822), max(333498272) in 5s
Relation stats: total(7742), max(4683118) in 7s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Using built-in tag processing pipeline

Going over pending ways...
        84949 ways are pending

Using 1 helper-processes
terminate called after throwing an instance of 'std::runtime_error'
  what():  middle_ram_t::relations_using_way is unimlpemented, and should not have been called. This is probably a bug, please report it at https://github.com/openstreetmap/osm2pgsql/issues
Aborted

**Comment by pnorman** [comment] 2015-03-27 15:53
duplicate of #213.

**Closed by pnorman** 2015-03-27 15:53 UTC
