### ISSUE TITLE
osm_timestamp it`s empty

### ISSUE THREAD

**Issue by baditaflorin** [openstreetmap/osm2pgsql#414] opened 2015-07-23 09:45 UTC
using the osm2pgsql from ubuntu 14.04 repo 
SVN version 0.84.0 (64bit id space)

osm2pgsql -s -S /usr/share/osm2pgsql/modified.style -C 12000 --extra-attributes --hstore-all -d database -U user canada-latest.osm.pbf

And i get the osm_user , osm_uid , osm_version , but the 
osm_timestamp get`s returned empty

#Relevant data 
node,way   osm_user            text  linear
node,way   osm_uid             text  linear
node,way   osm_version         text  linear
node,way   osm_timestamp       text  linear

**Comment by lonvia** [comment] 2015-07-23 11:44
duplicate of #137

**Closed by lonvia** 2015-07-23 11:44 UTC
