### ISSUE TITLE
timestamp doesn't appears in database

### ISSUE THREAD

**Issue by matejko94** [openstreetmap/osm2pgsql#780] opened 2017-08-12 06:54 UTC
I use parameters --hstore and --extra-attributes, but timestamp does not appear in database..

**Comment by lonvia** [comment] 2017-08-12 16:30
Works for me. There is an entry `osm_timestamp` in the hstore column.

What osm2pgsql version do you use? What is the exact command line? What input data do you use?

**Comment by matejko94** [comment] 2017-08-12 17:03
I am using 0.88.1 version in linux. 
Exact "command line" is in:
`["osm2pgsql", "--" + mode, "--database", db_name, "--cache", str(cache_size),
                      "--number-processes", str(osm2pgsql_number_processes), "--prefix", prefix_table,
                      "--slim", "--port", str(db_port), "--host", db_host,
                      "--username", db_user, "--latlong", "--password", "--keep-coastlines",
                      "--extra-attributes", "--hstore",
                      # "--style",style_file,
                      osm_files]`

Basicly I use last update from: http://download.geofabrik.de/europe/ for luxembourg country.

**Comment by lonvia** [comment] 2017-08-12 19:18
This is a very old version, please try with the most recent release.

If it still doesn't work, please paste the command actually executed, not a line of python code with expanded variables. If you use a custom style file then please make that available as well.

**Comment by pnorman** [comment] 2017-08-12 22:18
duplicate of #137 and fixed in 0.90.0

**Closed by pnorman** 2017-08-12 22:18 UTC

**Comment by matejko94** [comment] 2017-08-13 12:57
@lonvia @pnorman Thank you very much for quick response.
Sorry for a lot of questions, but I have another question. :) I want that osm2pgsql put polygons, lines into one table. Actually I want to export only camps from whole Europe. Is it possible solution to avoid 4 tables ?
