### ISSUE TITLE
many duplicate lines from relations

### ISSUE THREAD

**Issue by gruzk** [openstreetmap/osm2pgsql#772] opened 2017-07-18 05:54 UTC
It seems some relations are processed into duplicate lines.  On a full planet import I have around 237 thousand duplicates (all with osm_id negative).  My style file is unmodified.  I am using osm2pgsql release version 0.92.1 with the typical command line as follows...

``osm2pgsql -d <db> -C 34000 --cache-strategy optimized --number-processes 6 --multi-geometry --hstore -U <user> -c --flat-nodes nodes.tmp --slim --unlogged -S openstreetmap-carto.style -E 3395 -H xxx -W planet-160912.osm.pbf``

Duplicates are identified by counting the number of features with the same osm_id and way, and for which the count is greater than one.  Polygons and points do not contain any duplicates, only line and roads.

The worst example is a 700+km line "Asian Highway AH12" with osm_id -229600.  It has 132 duplicates on one particular section.  This relation in reality consists of only 79 unique parts but in the database has been created with 1043 parts (over 960 duplicates).

Currently I am removing the duplicates in postgresql with some SQL scripts after import, but it would be preferable not to have these duplicates created in the first place.  Is there a fix for osm2pgsql?

**Comment by pnorman** [comment] 2017-07-18 15:11
What query did you use to test this?

**Comment by gruzk** [comment] 2017-07-19 04:33
Something like this would do it:

select osm_id, way, count(*) from planet_osm_line group by osm_id, way having count(*) > 1;

If it returns any rows then there are duplicates.

**Comment by pnorman** [comment] 2017-07-19 19:39
Because AH12 is long enough to trigger long way splitting, I wonder if there's an interaction there.

**Comment by lonvia** [comment] 2017-07-23 18:17
osm2pgsql doesn't do multilines for route relations. If the route does not result in a linear geometry, it is split.

Duplicate of #677.

**Comment by gruzk** [comment] 2017-07-24 15:22
This is not about split lines, this is many identical lines.  It is not the same issue as #677.

**Comment by pnorman** [comment] 2017-07-24 18:56
`osm2pgsql -d osm2pgsql_test r229600.osm` reprodcues what is being described. The problem is a data error, not one with osm2pgsql. Some ways (e.g. 300785287) are a member of the relation many times.

**Comment by lonvia** [comment] 2017-07-24 19:17
I reopened to early. This is a data error. The example relation has tons of duplicate ways:

```
/tmp> wget -O r229600.osm http://www.openstreetmap.org/api/0.6/relation/229600
/tmp> sort r229600.osm | uniq -c | sort -n | tail -n 20
      2   <member type="way" ref="183114652" role=""/>
      2   <member type="way" ref="183114657" role=""/>
      2   <member type="way" ref="202974255" role=""/>
      2   <member type="way" ref="231932883" role=""/>
      2   <member type="way" ref="231932891" role=""/>
      2   <member type="way" ref="275144786" role=""/>
      2   <member type="way" ref="275144791" role=""/>
      2   <member type="way" ref="434973631" role=""/>
      2   <member type="way" ref="434973632" role=""/>
      4   <member type="way" ref="50287013" role=""/>
     32   <member type="way" ref="50640396" role=""/>
    127   <member type="way" ref="389995080" role=""/>
    132   <member type="way" ref="12859068" role=""/>
    132   <member type="way" ref="255519084" role=""/>
    132   <member type="way" ref="255519085" role=""/>
    132   <member type="way" ref="300785287" role=""/>
    132   <member type="way" ref="300785300" role=""/>
    132   <member type="way" ref="389995079" role=""/>
    132   <member type="way" ref="451280594" role=""/>
    132   <member type="way" ref="451280595" role=""/>
...

This is reflected in your database.

**Closed by lonvia** 2017-07-24 19:17 UTC
