### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vince-from-nice** [openstreetmap/osm2pgsql#290] opened 2015-02-13 21:18 UTC
Hello,

I have segfaults while osm2pgsql is reading my XML. The files are exported from JOSM and containing elements from the API test server (it's working fine with XML files containing elements from the live server).

```
turman@entropy:~/Workspace/GGTS$~/Software/osm2pgsql/bin/osm2pgsql -c -v -C 1000 -d osm_osm2pgsql_test ~/Workspace/JOSM/test-crash.osm
osm2pgsql SVN version 0.87.2-dev (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=1000MB, maxblocks=128000*8192, allocation method=3
Mid: Ram, scale=100

Reading in file: /home/turman/Workspace/JOSM/test-crash.osm
Erreur de segmentation

Logs with strace:

write(2, "\nReading in file: /home/turman/W"..., 61
Reading in file: /home/turman/Workspace/JOSM/test-crash.osm
) = 61
time(NULL)                              = 1423862107
brk(0x1813000)                          = 0x1813000
futex(0x7f206caff6e8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
time(NULL)                              = 1423862107
open("/home/turman/Workspace/JOSM/test-crash.osm", O_RDONLY) = 7
read(7, "<?xm", 4)                      = 4
read(7, "l version='1.0' encoding='UTF-8'"..., 4096) = 436
read(7, "", 4096)                       = 0
time([1423862107])                      = 1423862107
time([1423862107])                      = 1423862107
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
Erreur de segmentation
```

I've tried to find which XML elements was causing crashes and at the end I can see that even an very  basic XML content causes a crash :

``` xml
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' upload='true' generator='JOSM'>
  <node id='4298138009' visible='true' version='1' changeset='56614' lat='48.8437993' lon='2.3729329' />
  <node id='4298138026' visible='true' version='1' changeset='56614' lat='48.844187' lon='2.3723893' />
  <way id='4296639452' visible='true' version='1' changeset='56614'>
    <nd ref='4298138009' />
    <nd ref='4298138026' />
  </way>
</osm>
```

If I remove the `<way>` element there's no more segfault !

I was testing with the osm2pgsql package from Debian Wheezy (0.80) but I've the same behavior with the latest Git version

Thanks for the help, Vincent.

**Comment by jburgess777** [comment] 2015-02-13 23:30
The problem is that the maximum supported way ID is 2^31. The crash can be fixed by raising the upper limit using the patch below. I have verified that this prevents the crash but have not done any further testing.
```
diff --git a/middle-ram.cpp b/middle-ram.cpp
index 01deb43..3bb52ea 100644
--- a/middle-ram.cpp
+++ b/middle-ram.cpp
@@ -43,7 +43,7 @@
 
 #define BLOCK_SHIFT 10
 #define PER_BLOCK  (1 << BLOCK_SHIFT)
-#define NUM_BLOCKS (1 << (32 - BLOCK_SHIFT))
+#define NUM_BLOCKS (1 << (33 - BLOCK_SHIFT))
 
 static osmid_t id2block(osmid_t id)
 {
```

**Comment by pnorman** [comment] 2015-02-14 00:26
This would explain why it turns up on data from master.apis.dev.openstreetmap.org, where the current IDs have been manually increased.

I suspect other parts of osm2pgsql don't work above 2^31 and we'd have to give consideration to if we want to support way IDs like that, given we are at about 10% of that ID and a linear extrapolation gives us decades before we hit 2^31.

**Comment by vince-from-nice** [comment] 2015-02-14 10:49
Thanks @jburgess777  for the patch but it doesn't work for me, I still have the segfault :(

And I don't understand the problem: that limit of 2^31 on IDs exists only for ways but not for nodes ?

But an important thing that I forgot to mention: another guy from the talk-fr mailing list is able to read my XML files.  And we have environments quite similar : latest Git release on Debian Wheezy 64 bits...

**Comment by sletuffe** [comment] 2015-02-14 23:17
I tried with the provided sample file and it worked for me (or should I say it doesn't segfault). But I found that I was using the --slim option while you aren't.
Without the --slim option I do confirm the segfault on the osm2pgsql version I have as well.

A workaround for you might be to just add the --slim option, I re-tried with a way with tags and it looks it is imported well with the correct id.

**Comment by pnorman** [comment] 2015-02-15 03:33
@vince-from-nice what commit of osm2pgsql did you build?

**Comment by lonvia** [comment] 2015-02-15 08:40
It should be `#define NUM_BLOCKS (1 << (34 - BLOCK_SHIFT))` (33 bits for the ID + 1 bit for potential negative values).

**Comment by vince-from-nice** [comment] 2015-02-15 11:06
@lonvia : You're right, the patch is working with 34 not 33 ! Thanks :+1: 

@sletuffe : You're right too, it works with the --slim option (without the patch).

**Comment by vince-from-nice** [comment] 2015-02-15 11:48
@pnorman : I'm up to date so my build was on the latest commit (949423c01357).

**Comment by pnorman** [comment] 2015-02-21 09:18
#158 is a similar issue about something the cache doesn't store but there's no user-friendly message about.

**Comment by lonvia** [comment] 2019-10-29 19:55
Closing in favour of #965.

**Closed by lonvia** 2019-10-29 19:55 UTC
