### ISSUE TITLE
Osm2pgsql not generating data in polygon table for Multigeometry

### ISSUE THREAD

**Issue by RakeshGupta-tomtom** [openstreetmap/osm2pgsql#1877] opened 2023-01-06 17:00 UTC

**Comment by RakeshGupta-tomtom** [comment] 2023-01-06 17:00
osm2pgsql version 1.6.0  I have geometry which in multi polygon / multi geometry form , when I do osm2pgsql its not populating data to polygon table , but *rels (relation ) table populated correctly

**Comment by lonvia** [comment] 2023-01-06 17:24
You have already been told before to provide all information to reproduce your problem. The questions in the bug report form are there for a reason. Please open another issue and make sure to answer them all carefully.

Closing because of insufficient information.

**Closed by lonvia** 2023-01-06 17:24 UTC
