### ISSUE TITLE
osm2pgsql segment fault with large node numbers

### ISSUE THREAD

**Issue by bob-zscharnagk** [openstreetmap/osm2pgsql#578] opened 2016-05-04 06:15 UTC
Hi,

I on Ubuntu 14.4 running osm2pgsql (osm2pgsql SVN version 0.85.0 (64bit id space)) to import some map data and I get a segment fault.  This is the output:-

bob@oms:~$ osm2pgsql --append -C 16000 --cache-strategy sparse -v  /tmp/srtm.osm_01_01.pbf
osm2pgsql SVN version 0.85.0 (64bit id space)

Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
Setting up table: planet_osm_line
NOTICE:  table "planet_osm_line_tmp" does not exist, skipping
Setting up table: planet_osm_polygon
NOTICE:  table "planet_osm_polygon_tmp" does not exist, skipping
Setting up table: planet_osm_roads
NOTICE:  table "planet_osm_roads_tmp" does not exist, skipping
Using built-in tag processing pipeline
Allocating memory for sparse node cache
Node-cache: cache=16000MB, maxblocks=2048000*8192, allocation method=1
Mid: Ram, scale=100

Reading in file: /tmp/srtm.osm_01_01.pbf
Processing: Node(32170k 5361.7k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Segmentation fault (core dumped)

Removing '--cache-strategy optimized' or '--cache-strategy dense' causes the fault to happen before the 'Processing....' line is output!

I created a very small osm file from the data, shown below, and still get the error.

<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmconvert 0.8.5">
	<bounds minlat="-40.9499999" minlon="173.53" maxlat="-38.4699999" maxlon="178.2000002"/>
	<node id="1353500000000" lat="-38.7604166" lon="174.73375"/>
	<node id="1353500000001" lat="-38.7595833" lon="174.7345833"/>
	<node id="1353500000002" lat="-38.7604166" lon="174.7354166"/>
	<node id="1353500000003" lat="-38.76125" lon="174.7345833"/>
	<way id="1353500000000">
		<nd ref="1353500000000"/>
		<nd ref="1353500000001"/>
		<nd ref="1353500000002"/>
		<nd ref="1353500000003"/>
		<nd ref="1353500000000"/>
		<tag k="ele" v="-40"/>
		<tag k="contour" v="elevation"/>
		<tag k="contour_ext" v="elevation_minor"/>
	</way>
</osm>

If I change the node numbers by removing two of the zeros, as shown below, it works.

<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmconvert 0.8.5">
	<bounds minlat="-40.9499999" minlon="173.53" maxlat="-38.4699999" maxlon="178.2000002"/>
	<node id="13535000000" lat="-38.7604166" lon="174.73375"/>
	<node id="13535000001" lat="-38.7595833" lon="174.7345833"/>
	<node id="13535000002" lat="-38.7604166" lon="174.7354166"/>
	<node id="13535000003" lat="-38.76125" lon="174.7345833"/>
	<way id="13535000000">
		<nd ref="13535000000"/>
		<nd ref="13535000001"/>
		<nd ref="13535000002"/>
		<nd ref="13535000003"/>
		<nd ref="13535000000"/>
		<tag k="ele" v="-40"/>
		<tag k="contour" v="elevation"/>
		<tag k="contour_ext" v="elevation_minor"/>
	</way>
</osm>

Is this a bug or just my error somehow?

Thanks.

Bob

**Comment by lonvia** [comment] 2016-05-04 07:02
Looks like a duplicate of #290. You'll also find a workaround over there. In general, I would avoid working with way and relation ids larger than 2^31.

**Comment by bob-zscharnagk** [comment] 2016-05-04 09:43
Sorry didn't preview the OSM files well enough.

Had to attach them.

[STRM_small_failing.txt](https://github.com/openstreetmap/osm2pgsql/files/248209/STRM_small_failing.txt)
[STRM_small_working.txt](https://github.com/openstreetmap/osm2pgsql/files/248210/STRM_small_working.txt)


d to attached them instaed

**Comment by bob-zscharnagk** [comment] 2016-05-04 09:47
Ionvia,

I tried with --slim but get 'relation "planet_osm_nodes" does not exist' error which I thought was to do with using --drop on the initial load.  However I'm sure I reloaded without --drop!

There was a code change mentioned in #290 to increase the node and way numbers. Did that make it to the GIT code?

Should I download the code and compile with those changes?

Thanks.

**Comment by ImreSamu** [comment] 2016-05-04 10:04
my2c:  sometimes the [osmium renumber](https://github.com/osmcode/osmium-tool/blob/master/man/osmium-renumber.md)  is a viable alternative.  

So your `STRM_small_failing.txt` will be : 

```xml
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" upload="false" generator="osmium/1.3.0">
  <bounds minlon="173.5300000" minlat="-40.9499999" maxlon="178.2000002" maxlat="-38.4699999"/>
  <node id="1" lat="-38.7604166" lon="174.73375"/>
  <node id="2" lat="-38.7595833" lon="174.7345833"/>
  <node id="3" lat="-38.7604166" lon="174.7354166"/>
  <node id="4" lat="-38.76125" lon="174.7345833"/>
  <way id="1">
    <nd ref="1"/>
    <nd ref="2"/>
    <nd ref="3"/>
    <nd ref="4"/>
    <nd ref="1"/>
    <tag k="ele" v="-40"/>
    <tag k="contour" v="elevation"/>
    <tag k="contour_ext" v="elevation_minor"/>
  </way>
</osm>
```

**Comment by bob-zscharnagk** [comment] 2016-05-04 22:24
ImreSamu,  If the data I'm loading are elevation lines that overlay other maps would the node and way IDs be related to the node and way ID's for the maps? I'm thinking that as long as I have a full world of elevation lines I could renumber them all and that would work.  What do you think?

**Comment by ImreSamu** [comment] 2016-05-05 05:57
@bob-zscharnagk : I don't know your full workflow, and your background,  but renumbering all ID-s  - and not using any 'update' mechanism ->  probably should work. ( but need double testing ! )

The renumbering 'trick' makes the full workflow extremely complex, and the debugging will be very hard! 
so if you don't understand deeply  why the ID is important  -  **please don't use this method!**

**Comment by pnorman** [comment] 2016-05-05 06:43
duplicate of #290 

For the use case of contour lines, you're better off putting them in their own table and probably not involving osm2pgsql at all.

**Closed by pnorman** 2016-05-05 06:43 UTC
