### ISSUE TITLE
Feature request: deletion of relation members

### ISSUE THREAD

**Issue by kennykb** [openstreetmap/osm2pgsql#1325] opened 2020-11-17 02:18 UTC
I'm still trying to work with a schema that has a table one row per relation membership: that is, a table with columns 'relid', 'wayid', 'role' and 'idx', where a row represents "way W appears in route relation R at index X with role Y". (That's what route relations look like when fully normalised, and my application wants to go in either direction - from a way to a _set_ of routes, or from a route to its constituent ways. (This is the same application as in #1312.)

I may be missing something, but it strikes me that there's trouble with making this work in the flex backend. There are two issues:

(1) The 'osm2pgsql.process_relation' call cannot tell whether it's inserting or deleting a relation.

(2) There's no way to delete rows from the table that represents relation memberships, and they're not auto-deleted either.

What I'm doing:

(1) process_way in stage 1 does nothing special - obviously, ways are imported, but nothing about relation membership happens.

(2) process_relation is called when a route relation is created, updated or deleted, but doesn't know which action is being taken.
If a relation is a route, of the correct type, it creates a row in a 'shieldroute' table in the database: relation_id, route type, network, ref, and a 'changed' flag (set to true by 'osm2pgsql' and reset later by another program).  It also records in a Lua variable the member ways of the relation.

As rather a hack, if process_relation sees that it's being called a second time for the same relation, it removes the previous memberships from the Lua variables. This trick causes updates to function more or less correctly - the first call was the 'delete' portion of the update and the second is the 'insert'.  It does NOT result in correct functioning when relations are deleted, because the values from the first pass are still there.

(3) select_relation_members simply selects all members of route relations of the types that the application is managing.

(4) process_way in stage 2 checks that not only is the way a member of a route relation, but also that it is a highway and not something else (like a guidepost, a turn point, or a terminus). It then creates the rows in the 'shieldway' table that enumerates
relation memberships.  This has to be a way table and not a relation table, because osm2pgsql does not allow adding to a relation table from 'process_way'.

So, I face the following.

1. If a relation is modified, I can reinsert the ways in step (4). There's no way for me to clean up the obsolete relation memberships, so they will linger in 'shieldway'.  I deal with this - and it appears to work - on the SQL side, by doing

```sql
ALTER TABLE @PREFIX@_shieldway
ADD CONSTRAINT @PREFIX@_shieldway_fk_shieldroute
FOREIGN KEY (relid)
REFERENCES @PREFIX@_shieldroute(relid)
ON DELETE CASCADE;
```
This discards the excess rows when the old version of the relation is deleted.

2. If a relation is simply deleted, the foreign key constraint above will indeed discard the excess rows, but I'll still have them in the Lua variables from steps (2) and (3) above, so step (4) will immediately re-insert them!  I don't have a workaround for this; fortunately, deleting route relations is extremely rare.

At the very least, what I'd like to have is that when process_relation is called, the 'object' parameter should have a 'delete' flag that is true when deleting and false when inserting (or an 'action' parameter with values 'insert' and 'delete'), so that the code can at least not put back the rows representing members of a deleted relation.

Preferably, I'd also like to have an interface to delete from a node, way or relation table given the node ID, way ID or relation ID respectively, so that the ON DELETE CASCADE constraint can be replaced with explicit deletion from the Lua script. This might be tricky to design, since there's nothing that guarantees that the ID will be unique in any given table (for instance, if multiple routes run over the same way, shieldway will have multiple lines for that way. I'd welcome a discussion of this. For right now, the referential constraint is at least enough to keep me moving forward.

@joto What do you think? Am I making sense here?

**Comment by joto** [comment] 2020-11-17 16:21
Osm2pgsql is specifically designed to magically handle the updating for you, so that you don't have to think about it any more. That's why it doesn't tell you if something is new vs. it changed vs. it is deleted. But that only works if you let it do its job and not try to work around it.

I believe your thinking is unnecessarily complex here. You should be able to solve your problems without thinking about updates. (Sure there is a limit to what this approach can handle, but I don't think your use case can not be handled with this.)

Basically I see two options for you:

1. Have a "relation_members" table that will contain all relation members you are interested in. Define it with `define_relation_table()` and fill it in the relations callback, call `add_row()` for each relation member there. This approach makes sure that osm2pgsql will correctly remove entries from this table whenever the relation membership changes. Of course this table can't have any tags from the member ways in it, but you can define a VIEW merging this table with one filled in the ways callback.

2. Use the 2-stage processing. The `flex-config/route-relations.lua` example config does this.

**Comment by kennykb** [comment] 2020-11-17 17:38
> Use the 2-stage processing. The `flex-config/route-relations.lua` example config does this.

Can you walk me through how this happens? I'm not seeing it - and I'm fairly convinced that the example script - which I based my own processing on - has the exact same problem. Have you tested it with the following scenario?

Start with a database has already been loaded with a route R and a member way W. There will be one row in 'routes' describing the relation R. The 'highways' table will have a row for way W. In that row, `rel_ids` and `rel_refs` describe its membership in relation R. All is OK so far.

Now, apply an update that removes member way W from relation R and replaces it with member V. (Assume that no change has happened to either member; the route is simply following a different way.)

(a) Stage 1 `process_way` sees neither W nor V because neither way has changed.

(b) Stage 1 `process_relation` is called for the old relation.  It adds a row to `routes` corresponding to the deleted relation, duplicating (harmlessly) the row that's already there. It also records in `w2r` that W is a member of R.

(c) `process_relation_members` is called, and schedules way W for reprocessing.

(d) The old relation is deleted, and the redundant row in `routes` is removed. (I don't know when this happens relative to (c), but it's happening correctly, so no trouble here.)

(e) Stage 1 `process_relation` is called for the new relation. It adds a row to `routes` corresponding to the new version of the relation. It records in `w2r` that V is a member of R.

(f) `process_relation_members` is called, and schedules way V for reprocessing.

(g) Stage 2 `process_way` is called for way W. It creates an entry in `highways` corresponding to W's _former_ membership in relation R. This entry is _in addition to_ the entry in `highways` that was previously there, which has not been deleted, because way W is unchanged from its previous version. There are now two rows in `highways` both showing that W is a member of R. Both are wrong.

(h) Stage 2 `process_way` is called for way V. It creates an entry in `highways` corresponding to V's membership in relation R.  This is the only correct row among the three rows in `highways`.


The minimal fix, as I see it, would be:

(1) Add the `delete` flag that I requested, so that `process_relation` can check it, and _not_ add deleted memberships to `w2r`. That gets rid of the bad row in `highways` that was caused by inserting the member of a deleted relation in (g).
I work around this bad row by cleaning it up using a referential integrity constraint `ON DELETE CASCADE`.

(2) Allow `process_way` to create entries in a relation table, and make `highways` a relation table, so that the magical deletion would actually clean up the residual entries in `highways` that haven't been cleaned up because nothing has touched the ways.  (Right now, you can't insert into a relation table from 1anywhere but `process_relation`, which makes this cleanup impossible.) I don't have a 100% solution for this problem.  For the case of a _modified_ relation, I can work around it by detecting that `process_relation` has been called a second time for the same relation, and cleaning up `w2r` before putting in the new members. For the case of a deleted relation, I cannot do this, and so stage 2 `process_way` simply recreates the rows that the `ON DELETE CASCADE` deleted.

**Comment by joto** [comment] 2020-11-18 08:53
If you think there is an error in the processing logic, can you please provide a case (ie. OSM files) which show this error?

**Comment by kennykb** [comment] 2020-11-19 16:23
At last, I figured out what was going on.  I think this is 'just' a documentation problem.

When I defined the table with,
```lua
	shieldway_tbl = osm2pgsql.define_table{
	    name = prefix .. '_shieldway',
	    ids = { type = 'way', id_column = 'wayid' },
	    columns = {
	        { column = 'relid', type = 'int8' },
		{ column = 'idx', type = 'int4' },
	        { column = 'role', type = 'text'},
	    }
```
it did _not_ get cleaned up properly.  Replacing that definition with
```lua
	shieldway_tbl = osm2pgsql.define_way_table(
	    prefix .. '_shieldway', {
	        { column = 'relation_id', type = 'int8' },
		{ column = 'idx', type = 'int4' },
	        { column = 'role', type = 'text'},
	    }
	)
```
did get a proper cleanup without needing to jump through hoops. (All of the 'thinking too much' was the result of trying to make the first definition work!)

The reason for using `define_table` in the first place was that I'd read in the documentation:

| If you are using the `osm2pgsql.define_(node|way|relation|area)_table()` convenience functions, `osm2pgsql` will automatically create an id column named `(node|way|relation|area)_id`, respectively. If you want more control over the id column(s), use the `osm2pgsql.define_table()` function.

I'd had existing code that used the names 'wayid' and 'relid' for the columns, because I had tables of a similar structure before trying to switch to the `flex` back end.  I was trying to keep the names to keep the code and database changes as minimal as possible. That line in the documentation is what led me astray.  If the cleanup is not supposed to work with the `define_table` alternative, the documentation ought to be clarified. (Otherwise, there's still a bug very like what I described, but you need `define_table` to trigger it.)

Anyway, I'm making forward progress again - and now I have some simple, controlled test cases for 'create a relation', 'change relation tags', 'add a way to a relation', 'remove a way from a relation', 'modify a way within a relation', 'delete a relation' which will be the foundation of a unit test suite, so this exercise wasn't entirely in vain.

**Comment by joto** [comment] 2020-11-19 17:02
The `define_*_table()` functions are only thin wrappers around the `define_table()` function. It is unlikely that that was the problem. I just tested them again and I can't reproduce your problem with id tracking with them. If you can reproduce your problem in a small test case I will look at it.

> (PS: Does the manual say anywhere what the keyword options are for define_table? I got them from one of your posts elsewhere, but I don't see them in the manual.)

Yeah. The manual is incomplete there. I'll fix that.

**Comment by kennykb** [comment] 2020-11-19 19:10
OK, I'm working on paring down the failure to something that makes sense as a test case. There's something of a Heisen-bug about it; look at it too closely and it starts to behave.

**Comment by joto** [comment] 2020-11-23 09:01
Okay, I am closing this here now as "not reproducible". But please open a new issue if you have an example where osm2pgsql is doing the wrong thing.

**Closed by joto** 2020-11-23 09:01 UTC

**Comment by kennykb** [comment] 2020-11-27 20:13
Go ahead and leave it closed.  The explanation of the misbehaviour was that I was examining with a different set of tables than I was updating, because I'd neglected to change the table prefix in the Lua script when I changed it on the command line. Slim tables were going to one place and highway tables to another (see #1345 for a suggestion at mistake-proofing).
